/**
 * Safe --fix generators (P1.17)
 *
 * All generators are:
 * - Additive-only: create new files, never modify existing ones
 * - Idempotent: running twice produces no additional changes
 * - Non-destructive: existing files are never overwritten
 */

import type { RepoContext } from "../analyzers/analyzer.interface.js";
import type { DetectionResult } from "@prontiq/ariscan-schema";

/** Fix confidence level — determines auto-apply vs suggest-only classification. */
export type FixConfidence = "high" | "medium" | "low";

/** A proposed file change from --fix. */
export interface FixProposal {
  /** Relative path within the repo. */
  path: string;
  /** File content to write. */
  content: string;
  /** Why this file is being generated. */
  rationale: string;
  /** Which ARI criterion this addresses. */
  criterion: string;
  /** Whether the file already exists (skip if true). */
  alreadyExists: boolean;
  /** Confidence level: high = auto-apply, medium = suggest, low = manual review. */
  confidence: FixConfidence;
}

/**
 * Generate all fix proposals for a repository.
 * Returns proposals for files that don't yet exist.
 */
export async function generateFixProposals(
  context: RepoContext,
  detection: DetectionResult | undefined,
): Promise<FixProposal[]> {
  const proposals: FixProposal[] = [];

  const [
    agentsMd,
    agentignore,
    devcontainer,
    providerSkeleton,
    tsconfigFix,
    nvmrc,
    preCommit,
    codeowners,
  ] = await Promise.all([
    generateAgentsMd(context, detection),
    generateAgentignore(context, detection),
    generateDevcontainer(context, detection),
    generateProviderSkeleton(context, detection),
    generateTsconfigStrictness(context, detection),
    generateNvmrc(context, detection),
    generatePreCommitHooks(context, detection),
    generateCodeowners(context),
  ]);

  proposals.push(agentsMd, agentignore, devcontainer, providerSkeleton);

  // Conditional proposals: only include if applicable
  for (const fix of [tsconfigFix, nvmrc, preCommit, codeowners]) {
    if (fix) {
      proposals.push(fix);
    }
  }

  return proposals;
}

/**
 * Generate an AGENTS.md with additive-only content.
 * Per Gloaguen et al. (2026): only include information agents can't discover independently.
 */
async function generateAgentsMd(
  context: RepoContext,
  detection: DetectionResult | undefined,
): Promise<FixProposal> {
  const exists = await context.fileExists("AGENTS.md");

  // Discover existing info to avoid duplication
  const pkgJson = await context.readJson<Record<string, unknown>>("package.json");
  const readme = await context.readFile("README.md");

  const sections: string[] = [];

  sections.push("# AGENTS.md");
  sections.push("");
  sections.push("<!-- Generated by ariscan --fix. Review and customize for your project. -->");
  sections.push("");

  // Build & test commands — only if not obvious from package.json scripts
  sections.push("## Build & Test Commands");
  sections.push("");
  sections.push("<!-- TODO(ARI-CTX-001): Add the exact commands agents should use. -->");
  sections.push("<!-- Only include commands that aren't obvious from package.json/Makefile. -->");
  sections.push("");

  if (pkgJson && typeof pkgJson === "object" && "scripts" in pkgJson) {
    const scripts = pkgJson.scripts as Record<string, string>;
    const commands: string[] = [];
    if (scripts.install || scripts.prepare) commands.push("# install dependencies first");
    if (scripts.build) commands.push(`# build: ${getPackageManager(context)} build`);
    if (scripts.test) commands.push(`# test: ${getPackageManager(context)} test`);
    if (scripts.lint) commands.push(`# lint: ${getPackageManager(context)} lint`);
    if (scripts.typecheck) commands.push(`# typecheck: ${getPackageManager(context)} typecheck`);

    if (commands.length > 0) {
      sections.push("```bash");
      sections.push(...commands);
      sections.push("```");
      sections.push("");
    }
  } else {
    // Non-Node projects: detect from common files
    const hasMakefile = await context.fileExists("Makefile");
    const hasCargoToml = await context.fileExists("Cargo.toml");
    const hasGoMod = await context.fileExists("go.mod");
    const hasPyproject = await context.fileExists("pyproject.toml");

    sections.push("```bash");
    if (hasMakefile) sections.push("# See Makefile for available targets");
    if (hasCargoToml) sections.push("# cargo build && cargo test");
    if (hasGoMod) sections.push("# go build ./... && go test ./...");
    if (hasPyproject) sections.push("# pip install -e . && pytest");
    if (!hasMakefile && !hasCargoToml && !hasGoMod && !hasPyproject) {
      sections.push("# TODO: Add your build and test commands here");
    }
    sections.push("```");
    sections.push("");
  }

  // Architecture constraints — always additive
  sections.push("## Architecture & Constraints");
  sections.push("");
  sections.push(
    "<!-- TODO(ARI-CTX-002): Document constraints agents can't discover from code. -->",
  );
  sections.push("<!-- Examples: -->");
  sections.push('<!-- - "Do NOT use library X because of Y" -->');
  sections.push('<!-- - "Always use the abstraction layer in src/db/, never raw SQL" -->');
  sections.push('<!-- - "Import extensions must use .js for ESM compatibility" -->');
  sections.push("");

  // Language/framework context from detection
  if (detection) {
    const primaryLang = detection.languages.find((l) => l.primary);
    if (primaryLang) {
      sections.push(`Primary language: ${primaryLang.language}`);
    }
    if (detection.frameworks.length > 0) {
      sections.push(`Frameworks: ${detection.frameworks.map((f) => f.framework).join(", ")}`);
    }
    if (detection.monorepo) {
      sections.push(
        `Monorepo: ${detection.monorepo.tool} (${detection.monorepo.packages.length} packages)`,
      );
    }
    sections.push("");
  }

  // Testing patterns — always useful for agents
  sections.push("## Testing Patterns");
  sections.push("");
  sections.push("<!-- TODO(ARI-TST-001): Document test conventions agents should follow. -->");
  sections.push("<!-- Examples: -->");
  sections.push('<!-- - "Use vitest, not jest" -->');
  sections.push('<!-- - "Mock filesystem via RepoContext, never use real fs in tests" -->');
  sections.push('<!-- - "Test files go in __tests__/ directories" -->');
  sections.push("");

  // Do NOT section — critical for agents
  sections.push("## Do NOT");
  sections.push("");
  sections.push("<!-- TODO(ARI-CTX-003): List explicit prohibitions. -->");
  sections.push("<!-- These are the most valuable instructions for AI agents. -->");
  sections.push("<!-- Examples: -->");
  sections.push("<!-- - Don't use `any` type — use `unknown` with type narrowing -->");
  sections.push("<!-- - Don't import without .js extension -->");
  sections.push("<!-- - Don't add console.log — use the logger -->");
  sections.push("");

  // Check that we're not duplicating README content
  const content = sections.join("\n");
  const readmeDuplication = readme ? computeOverlap(content, readme) : 0;
  if (readmeDuplication > 0.3) {
    // Too much duplication — strip the detected info section
    const filteredSections = sections.filter(
      (s) =>
        !s.startsWith("Primary language:") &&
        !s.startsWith("Frameworks:") &&
        !s.startsWith("Monorepo:"),
    );
    return {
      path: "AGENTS.md",
      content: filteredSections.join("\n"),
      rationale:
        "Provides agent-specific context not discoverable from code. TODOs guide human review.",
      criterion: "ARI-CTX-001",
      alreadyExists: exists,
      confidence: "high" as FixConfidence,
    };
  }

  return {
    path: "AGENTS.md",
    content,
    rationale:
      "Provides agent-specific context not discoverable from code. TODOs guide human review.",
    criterion: "ARI-CTX-001",
    alreadyExists: exists,
    confidence: "high" as FixConfidence,
  };
}

/**
 * Generate an .agentignore file with sensible defaults.
 */
async function generateAgentignore(
  context: RepoContext,
  detection: DetectionResult | undefined,
): Promise<FixProposal> {
  const exists = await context.fileExists(".agentignore");

  const lines: string[] = [];
  lines.push("# .agentignore — Files excluded from AI agent context");
  lines.push("# Generated by ariscan --fix. Customize for your project.");
  lines.push("# Syntax: .gitignore-compatible glob patterns");
  lines.push("");

  // Universal patterns
  lines.push("# Build artifacts");
  lines.push("dist/");
  lines.push("build/");
  lines.push(".next/");
  lines.push("out/");
  lines.push(".turbo/");
  lines.push("");

  lines.push("# Dependencies");
  lines.push("node_modules/");
  lines.push("vendor/");
  lines.push(".venv/");
  lines.push("__pycache__/");
  lines.push("");

  lines.push("# Lockfiles (high token cost, low agent value)");
  lines.push("package-lock.json");
  lines.push("pnpm-lock.yaml");
  lines.push("yarn.lock");
  lines.push("Cargo.lock");
  lines.push("go.sum");
  lines.push("poetry.lock");
  lines.push("composer.lock");
  lines.push("");

  lines.push("# Generated files");
  lines.push("*.generated.*");
  lines.push("*.min.js");
  lines.push("*.min.css");
  lines.push("*.map");
  lines.push("*.d.ts");
  lines.push("");

  lines.push("# Coverage & reports");
  lines.push("coverage/");
  lines.push(".nyc_output/");
  lines.push("htmlcov/");
  lines.push("");

  lines.push("# IDE & editor");
  lines.push(".idea/");
  lines.push("*.swp");
  lines.push("*.swo");
  lines.push("");

  // Language-specific patterns
  const primaryLang = detection?.languages.find((l) => l.primary);
  if (primaryLang) {
    switch (primaryLang.language) {
      case "python":
        lines.push("# Python-specific");
        lines.push("*.pyc");
        lines.push("*.egg-info/");
        lines.push(".tox/");
        lines.push(".mypy_cache/");
        lines.push("");
        break;
      case "go":
        lines.push("# Go-specific");
        lines.push("*.test");
        lines.push("");
        break;
      case "rust":
        lines.push("# Rust-specific");
        lines.push("target/");
        lines.push("");
        break;
      case "java":
        lines.push("# Java-specific");
        lines.push("*.class");
        lines.push("target/");
        lines.push(".gradle/");
        lines.push("");
        break;
    }
  }

  return {
    path: ".agentignore",
    content: lines.join("\n"),
    rationale: "Excludes high-token, low-value files from agent context to reduce inference cost.",
    criterion: "ARI-CTX-004",
    alreadyExists: exists,
    confidence: "high" as FixConfidence,
  };
}

/**
 * Generate a .devcontainer/devcontainer.json based on detected stack.
 */
async function generateDevcontainer(
  context: RepoContext,
  detection: DetectionResult | undefined,
): Promise<FixProposal> {
  const exists = await context.fileExists(".devcontainer/devcontainer.json");

  const primaryLang = detection?.languages.find((l) => l.primary);
  const langName = primaryLang?.language ?? "universal";

  const image = getDevcontainerImage(langName);
  const features = getDevcontainerFeatures(langName, detection);
  const postCreateCommand = getPostCreateCommand(context, langName);

  const config: Record<string, unknown> = {
    name: "Development Container",
    image,
    ...(Object.keys(features).length > 0 ? { features } : {}),
    postCreateCommand: await postCreateCommand,
    customizations: {
      vscode: {
        extensions: getVscodeExtensions(langName),
      },
    },
    "// generated-by": "ariscan --fix",
    "// TODO(ARI-ENV-001)": "Customize image, features, and postCreateCommand for your project",
  };

  return {
    path: ".devcontainer/devcontainer.json",
    content: JSON.stringify(config, null, 2) + "\n",
    rationale: "Reproducible dev environment reduces onboarding time for both humans and agents.",
    criterion: "ARI-ENV-001",
    alreadyExists: exists,
    confidence: "high" as FixConfidence,
  };
}

/**
 * Generate a provider pattern skeleton for detected cloud SDK usage.
 * Helps teams wrap direct SDK calls behind interfaces for testability.
 */
async function generateProviderSkeleton(
  context: RepoContext,
  detection: DetectionResult | undefined,
): Promise<FixProposal> {
  const primaryLang = detection?.languages.find((l) => l.primary);
  const langName = primaryLang?.language ?? "typescript";

  // Detect cloud SDK usage to determine which providers to scaffold
  const sdkPatterns = [
    { pattern: /\b(AWS|@aws-sdk|aws-sdk)\b/i, name: "AWS", service: "S3" },
    { pattern: /\b(azure|@azure)\b/i, name: "Azure", service: "BlobStorage" },
    { pattern: /\b(google\.cloud|@google-cloud)\b/i, name: "GCP", service: "CloudStorage" },
  ];

  const detectedSdks: Array<{ name: string; service: string }> = [];
  const sourceFiles = context.files.filter(
    (f) =>
      /\.[jt]sx?$|\.py$|\.go$|\.java$|\.cs$|\.rb$|\.rs$/.test(f) &&
      !f.includes("node_modules") &&
      !f.includes("test") &&
      !f.includes("spec"),
  );
  const sampled = sourceFiles.slice(0, 30);

  for (const file of sampled) {
    const content = await context.readFile(file);
    if (!content) continue;
    for (const sdk of sdkPatterns) {
      if (sdk.pattern.test(content) && !detectedSdks.some((d) => d.name === sdk.name)) {
        detectedSdks.push({ name: sdk.name, service: sdk.service });
      }
    }
  }

  // Determine the best path for the provider file
  const providerPath =
    langName === "typescript" || langName === "javascript"
      ? "src/providers/storage.provider.ts"
      : langName === "python"
        ? "src/providers/storage_provider.py"
        : langName === "go"
          ? "internal/providers/storage.go"
          : "src/providers/StorageProvider." +
            (langName === "java" ? "java" : langName === "c#" ? "cs" : "ts");

  const exists = await context.fileExists(providerPath);

  const content = generateProviderContent(langName, detectedSdks);

  return {
    path: providerPath,
    content,
    rationale:
      "Provider pattern decouples source code from cloud SDKs, making tests deterministic. " +
      "Agents can swap real implementations for mocks without modifying business logic.",
    criterion: "ARI-TST-001",
    alreadyExists: exists,
    confidence: "medium" as FixConfidence,
  };
}

function generateProviderContent(
  language: string,
  detectedSdks: Array<{ name: string; service: string }>,
): string {
  const sdkComment =
    detectedSdks.length > 0
      ? `Detected SDK usage: ${detectedSdks.map((s) => s.name).join(", ")}`
      : "No cloud SDK detected — generic storage provider scaffold";

  if (language === "typescript" || language === "javascript") {
    return [
      "/**",
      " * Storage Provider — Dependency injection pattern for cloud SDK abstraction.",
      ` * ${sdkComment}`,
      " * Generated by ariscan --fix. Customize for your project.",
      " *",
      " * TODO(ARI-TST-001): Implement concrete providers for your cloud services.",
      " * TODO(ARI-TST-001): Replace direct SDK calls in source files with this interface.",
      " */",
      "",
      "/** Abstract storage interface — implement per cloud provider. */",
      "export interface StorageProvider {",
      "  get(key: string): Promise<Buffer | null>;",
      "  put(key: string, data: Buffer): Promise<void>;",
      "  delete(key: string): Promise<void>;",
      "  list(prefix: string): Promise<string[]>;",
      "}",
      "",
      "/** In-memory implementation for tests. */",
      "export class InMemoryStorageProvider implements StorageProvider {",
      "  private store = new Map<string, Buffer>();",
      "",
      "  async get(key: string): Promise<Buffer | null> {",
      "    return this.store.get(key) ?? null;",
      "  }",
      "",
      "  async put(key: string, data: Buffer): Promise<void> {",
      "    this.store.set(key, data);",
      "  }",
      "",
      "  async delete(key: string): Promise<void> {",
      "    this.store.delete(key);",
      "  }",
      "",
      "  async list(prefix: string): Promise<string[]> {",
      "    return [...this.store.keys()].filter((k) => k.startsWith(prefix));",
      "  }",
      "}",
      "",
      "// TODO: Add concrete implementations (e.g., S3StorageProvider, AzureBlobProvider)",
      "",
    ].join("\n");
  }

  if (language === "python") {
    return [
      '"""',
      "Storage Provider — Dependency injection pattern for cloud SDK abstraction.",
      `${sdkComment}`,
      "Generated by ariscan --fix. Customize for your project.",
      "",
      "TODO(ARI-TST-001): Implement concrete providers for your cloud services.",
      '"""',
      "",
      "from abc import ABC, abstractmethod",
      "from typing import Optional",
      "",
      "",
      "class StorageProvider(ABC):",
      '    """Abstract storage interface — implement per cloud provider."""',
      "",
      "    @abstractmethod",
      "    async def get(self, key: str) -> Optional[bytes]:",
      "        ...",
      "",
      "    @abstractmethod",
      "    async def put(self, key: str, data: bytes) -> None:",
      "        ...",
      "",
      "    @abstractmethod",
      "    async def delete(self, key: str) -> None:",
      "        ...",
      "",
      "    @abstractmethod",
      "    async def list(self, prefix: str) -> list[str]:",
      "        ...",
      "",
      "",
      "class InMemoryStorageProvider(StorageProvider):",
      '    """In-memory implementation for tests."""',
      "",
      "    def __init__(self) -> None:",
      "        self._store: dict[str, bytes] = {}",
      "",
      "    async def get(self, key: str) -> Optional[bytes]:",
      "        return self._store.get(key)",
      "",
      "    async def put(self, key: str, data: bytes) -> None:",
      "        self._store[key] = data",
      "",
      "    async def delete(self, key: str) -> None:",
      "        self._store.pop(key, None)",
      "",
      "    async def list(self, prefix: str) -> list[str]:",
      "        return [k for k in self._store if k.startswith(prefix)]",
      "",
    ].join("\n");
  }

  if (language === "go") {
    return [
      "package providers",
      "",
      `// ${sdkComment}`,
      "// Generated by ariscan --fix. Customize for your project.",
      "// TODO(ARI-TST-001): Implement concrete providers for your cloud services.",
      "",
      'import "context"',
      "",
      "// StorageProvider abstracts cloud storage operations.",
      "type StorageProvider interface {",
      "\tGet(ctx context.Context, key string) ([]byte, error)",
      "\tPut(ctx context.Context, key string, data []byte) error",
      "\tDelete(ctx context.Context, key string) error",
      "\tList(ctx context.Context, prefix string) ([]string, error)",
      "}",
      "",
      "// InMemoryStorage implements StorageProvider for tests.",
      "type InMemoryStorage struct {",
      "\tstore map[string][]byte",
      "}",
      "",
      "// NewInMemoryStorage creates a new in-memory storage.",
      "func NewInMemoryStorage() *InMemoryStorage {",
      "\treturn &InMemoryStorage{store: make(map[string][]byte)}",
      "}",
      "",
    ].join("\n");
  }

  // Default fallback (TypeScript)
  return [
    "// Storage Provider — Generated by ariscan --fix",
    `// ${sdkComment}`,
    "// TODO(ARI-TST-001): Customize for your project.",
    "",
    "export interface StorageProvider {",
    "  get(key: string): Promise<Buffer | null>;",
    "  put(key: string, data: Buffer): Promise<void>;",
    "  delete(key: string): Promise<void>;",
    "}",
    "",
  ].join("\n");
}

/**
 * Generate a tsconfig.json with strict settings if none exists,
 * or suggest strictness improvements for existing configs.
 * P2.07: Risk-aware --fix expansion.
 *
 * Classification:
 * - No tsconfig.json: Auto-apply (high confidence) — creates new file.
 * - Existing tsconfig.json without strict: Suggest-only — marks alreadyExists.
 */
async function generateTsconfigStrictness(
  context: RepoContext,
  detection: DetectionResult | undefined,
): Promise<FixProposal | null> {
  // Only applicable to TypeScript/JavaScript projects
  const primaryLang = detection?.languages.find((l) => l.primary);
  if (!primaryLang) return null;
  if (primaryLang.language !== "typescript" && primaryLang.language !== "javascript") return null;

  const exists = await context.fileExists("tsconfig.json");

  if (exists) {
    // Read existing config to check strictness
    const existing = await context.readJson<TsconfigShape>("tsconfig.json");
    if (!existing?.compilerOptions) {
      // Can't parse — suggest only
      return {
        path: "tsconfig.json",
        content: generateStrictTsconfig(),
        rationale:
          "Existing tsconfig.json could not be parsed. Suggested strict config for reference. " +
          "Review and merge manually.",
        criterion: "ARI-BLD-001",
        alreadyExists: true,
        confidence: "low" as FixConfidence,
      };
    }

    const opts = existing.compilerOptions;
    const missingStrict: string[] = [];

    if (opts.strict !== true) missingStrict.push('"strict": true');
    if (opts.strictNullChecks !== true && opts.strict !== true)
      missingStrict.push('"strictNullChecks": true');
    if (opts.noImplicitAny !== true && opts.strict !== true)
      missingStrict.push('"noImplicitAny": true');
    if (opts.noUncheckedIndexedAccess !== true)
      missingStrict.push('"noUncheckedIndexedAccess": true');
    if (opts.exactOptionalPropertyTypes !== true)
      missingStrict.push('"exactOptionalPropertyTypes": true');

    if (missingStrict.length === 0) {
      // Already fully strict — no fix needed
      return null;
    }

    return {
      path: "tsconfig.json",
      content: generateStrictTsconfig(),
      rationale:
        `Existing tsconfig.json is missing: ${missingStrict.join(", ")}. ` +
        "Suggested strict config for reference — review and merge manually. " +
        "Do NOT auto-apply: modifying existing tsconfig may break builds.",
      criterion: "ARI-BLD-001",
      alreadyExists: true,
      confidence: "low" as FixConfidence,
    };
  }

  // No tsconfig.json exists — safe to auto-apply (high confidence)
  return {
    path: "tsconfig.json",
    content: generateStrictTsconfig(),
    rationale:
      "Creates a strict TypeScript config. Strict mode catches more errors at compile time " +
      "and gives AI agents higher confidence in type information.",
    criterion: "ARI-BLD-001",
    alreadyExists: false,
    confidence: "high" as FixConfidence,
  };
}

/**
 * Generate a .nvmrc file pinning the Node.js version.
 * Reads `engines.node` from package.json; falls back to LTS (22).
 * Only applicable to Node/TypeScript/JavaScript projects.
 */
async function generateNvmrc(
  context: RepoContext,
  detection: DetectionResult | undefined,
): Promise<FixProposal | null> {
  const primaryLang = detection?.languages.find((l) => l.primary);
  if (!primaryLang) return null;
  if (primaryLang.language !== "typescript" && primaryLang.language !== "javascript") return null;

  // Check if any version pinning file already exists
  const versionFiles = [".nvmrc", ".node-version", ".tool-versions"];
  let anyExists = false;
  for (const f of versionFiles) {
    if (await context.fileExists(f)) {
      anyExists = true;
      break;
    }
  }

  // Extract Node version from engines field
  let nodeVersion = "22";
  const pkgJson = await context.readJson<Record<string, unknown>>("package.json");
  if (pkgJson && typeof pkgJson === "object" && "engines" in pkgJson) {
    const engines = pkgJson.engines as Record<string, string> | undefined;
    if (engines?.node) {
      // Extract major version from patterns like ">=22.0.0", "^22", "22.x", "22"
      const match = /(\d+)/.exec(engines.node);
      if (match?.[1]) {
        nodeVersion = match[1];
      }
    }
  }

  return {
    path: ".nvmrc",
    content: `${nodeVersion}\n`,
    rationale:
      "Pins Node.js version for reproducible builds. Agents and CI use this to select the correct runtime.",
    criterion: "ARI-ENV-003",
    alreadyExists: anyExists,
    confidence: "high" as FixConfidence,
  };
}

/**
 * Generate a .husky/pre-commit hook for lint + typecheck.
 * Only applicable to Node.js projects with package.json.
 */
async function generatePreCommitHooks(
  context: RepoContext,
  detection: DetectionResult | undefined,
): Promise<FixProposal | null> {
  // Only for Node ecosystem projects
  const hasPackageJson = await context.fileExists("package.json");
  if (!hasPackageJson) return null;

  const primaryLang = detection?.languages.find((l) => l.primary);
  if (primaryLang && primaryLang.language !== "typescript" && primaryLang.language !== "javascript")
    return null;

  const exists = await context.fileExists(".husky/pre-commit");

  const pm = getPackageManager(context);
  const pkgJson = await context.readJson<Record<string, unknown>>("package.json");
  const scripts =
    pkgJson && typeof pkgJson === "object" && "scripts" in pkgJson
      ? (pkgJson.scripts as Record<string, string>)
      : {};

  const commands: string[] = [];
  if (scripts.lint) commands.push(`${pm} lint`);
  if (scripts.typecheck) commands.push(`${pm} typecheck`);
  if (commands.length === 0) {
    // No lint/typecheck scripts — not useful to generate
    return null;
  }

  const content = [
    "#!/usr/bin/env sh",
    '. "$(dirname -- "$0")/_/husky.sh"',
    "",
    "# Pre-commit checks: lint and typecheck",
    "# Generated by ariscan --fix. Customize for your project.",
    "# TODO(ARI-SEC-002): Add project-specific pre-commit checks.",
    "",
    ...commands.map((c) => c),
    "",
  ].join("\n");

  return {
    path: ".husky/pre-commit",
    content,
    rationale:
      "Pre-commit hooks catch lint and type errors before they enter the codebase. " +
      "Reduces review burden for both human and AI-generated code.",
    criterion: "ARI-SEC-002",
    alreadyExists: exists,
    confidence: "medium" as FixConfidence,
  };
}

/**
 * Generate a .github/CODEOWNERS template.
 * Template-based (not git-blame) since RepoContext is read-only filesystem.
 */
async function generateCodeowners(context: RepoContext): Promise<FixProposal | null> {
  const codeownersLocations = ["CODEOWNERS", ".github/CODEOWNERS", "docs/CODEOWNERS"];

  let anyExists = false;
  for (const loc of codeownersLocations) {
    if (await context.fileExists(loc)) {
      anyExists = true;
      break;
    }
  }

  // Detect common paths to suggest ownership for
  const hasGithub = context.files.some((f) => f.startsWith(".github/"));
  const hasSrc = context.files.some((f) => f.startsWith("src/"));
  const hasPackages = context.files.some((f) => f.startsWith("packages/"));

  const lines: string[] = [];
  lines.push("# CODEOWNERS — Define code review ownership");
  lines.push("# Generated by ariscan --fix. Customize with your team's GitHub usernames.");
  lines.push(
    "# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners",
  );
  lines.push("");
  lines.push("# TODO(ARI-SEC-001): Replace @TODO-add-default-owner with your team/user.");
  lines.push("");
  lines.push("# Default owner for everything");
  lines.push("* @TODO-add-default-owner");
  lines.push("");
  lines.push("# Security-sensitive paths — require security team review");
  if (hasGithub) {
    lines.push(".github/ @TODO-add-security-owner");
  }
  lines.push("*.lock @TODO-add-default-owner");
  lines.push(".env* @TODO-add-security-owner");
  lines.push("");

  if (hasSrc) {
    lines.push("# Source code");
    lines.push("src/ @TODO-add-default-owner");
    lines.push("");
  }

  if (hasPackages) {
    lines.push("# Packages (monorepo)");
    lines.push("packages/ @TODO-add-default-owner");
    lines.push("");
  }

  return {
    path: ".github/CODEOWNERS",
    content: lines.join("\n"),
    rationale:
      "CODEOWNERS ensures critical paths get reviewed by the right people. " +
      "Prevents AI-generated code from merging without appropriate oversight.",
    criterion: "ARI-SEC-001",
    alreadyExists: anyExists,
    confidence: "low" as FixConfidence,
  };
}

interface TsconfigShape {
  compilerOptions?: {
    strict?: boolean;
    strictNullChecks?: boolean;
    noImplicitAny?: boolean;
    noUncheckedIndexedAccess?: boolean;
    exactOptionalPropertyTypes?: boolean;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

function generateStrictTsconfig(): string {
  const config = {
    compilerOptions: {
      strict: true,
      noUncheckedIndexedAccess: true,
      exactOptionalPropertyTypes: true,
      noEmit: true,
      target: "ES2022",
      module: "Node16",
      moduleResolution: "Node16",
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
      declaration: true,
      declarationMap: true,
      sourceMap: true,
    },
    include: ["src"],
    exclude: ["node_modules", "dist"],
    "// generated-by": "ariscan --fix",
    "// TODO(ARI-BLD-001)":
      "Review and customize compiler options for your project. strict: true enables all strict type checks.",
  };

  return JSON.stringify(config, null, 2) + "\n";
}

// Helper functions

function getPackageManager(context: RepoContext): string {
  if (context.files.some((f) => f === "pnpm-lock.yaml" || f === "pnpm-workspace.yaml"))
    return "pnpm";
  if (context.files.some((f) => f === "yarn.lock")) return "yarn";
  return "npm";
}

function getDevcontainerImage(language: string): string {
  switch (language) {
    case "typescript":
    case "javascript":
      return "mcr.microsoft.com/devcontainers/typescript-node:22";
    case "python":
      return "mcr.microsoft.com/devcontainers/python:3.12";
    case "go":
      return "mcr.microsoft.com/devcontainers/go:1.22";
    case "rust":
      return "mcr.microsoft.com/devcontainers/rust:latest";
    case "java":
      return "mcr.microsoft.com/devcontainers/java:21";
    default:
      return "mcr.microsoft.com/devcontainers/base:ubuntu";
  }
}

function getDevcontainerFeatures(
  language: string,
  detection: DetectionResult | undefined,
): Record<string, Record<string, unknown>> {
  const features: Record<string, Record<string, unknown>> = {};

  // Git always useful
  features["ghcr.io/devcontainers/features/git:1"] = {};

  // Add GitHub CLI
  features["ghcr.io/devcontainers/features/github-cli:1"] = {};

  if (language === "typescript" || language === "javascript") {
    // Check for pnpm
    if (detection?.monorepo?.tool === "pnpm-workspaces") {
      features["ghcr.io/devcontainers/features/node:1"] = { nodeVersion: "22" };
    }
  }

  return features;
}

async function getPostCreateCommand(context: RepoContext, language: string): Promise<string> {
  const hasPnpmLock = context.files.some((f) => f === "pnpm-lock.yaml");
  const hasYarnLock = context.files.some((f) => f === "yarn.lock");
  const hasPackageJson = context.files.some((f) => f === "package.json");

  if (hasPnpmLock) return "corepack enable && pnpm install";
  if (hasYarnLock) return "corepack enable && yarn install";
  if (hasPackageJson) return "npm install";

  switch (language) {
    case "python":
      return "pip install -e '.[dev]'";
    case "go":
      return "go mod download";
    case "rust":
      return "cargo build";
    default:
      return "echo 'TODO: Add your setup command'";
  }
}

function getVscodeExtensions(language: string): string[] {
  const base = ["editorconfig.editorconfig"];
  switch (language) {
    case "typescript":
    case "javascript":
      return [...base, "dbaeumer.vscode-eslint", "esbenp.prettier-vscode"];
    case "python":
      return [...base, "ms-python.python", "ms-python.vscode-pylance"];
    case "go":
      return [...base, "golang.go"];
    case "rust":
      return [...base, "rust-lang.rust-analyzer"];
    case "java":
      return [...base, "vscjava.vscode-java-pack"];
    default:
      return base;
  }
}

/**
 * Compute rough overlap between two text strings.
 * Returns fraction (0-1) of lines in `a` that also appear in `b`.
 */
function computeOverlap(a: string, b: string): number {
  const aLines = a.split("\n").filter((l) => l.trim().length > 10);
  if (aLines.length === 0) return 0;

  const bLines = new Set(b.split("\n").map((l) => l.trim()));
  let matches = 0;
  for (const line of aLines) {
    if (bLines.has(line.trim())) matches++;
  }
  return matches / aLines.length;
}
