import { type PillarId, PILLAR_NAMES, type Finding } from "@prontiq/ariscan-schema";
import type { PillarAnalyzer, RepoContext } from "./analyzer.interface.js";
import { buildPillarResult } from "./shared.js";

const PILLAR: PillarId = "P1";

const CONTEXT_FILES = [
  "AGENTS.md",
  "CLAUDE.md",
  ".cursorrules",
  ".cursor/rules",
  ".github/copilot-instructions.md",
  ".aider.conf.yml",
  ".aiderignore",
  ".agentignore",
  ".mcp.json",
  "mcp.config.js",
  ".claude/settings.json",
] as const;

/** Directory patterns to check (any file under these dirs counts as a match) */
const CONTEXT_DIRS = [".claude/commands"] as const;

/** Agent-to-context-file mapping for cross-agent compatibility report */
interface AgentMapping {
  agent: string;
  files: readonly string[];
  dirs?: readonly string[];
}

const AGENT_MAPPINGS: readonly AgentMapping[] = [
  {
    agent: "Claude Code",
    files: ["CLAUDE.md", ".claude/settings.json"],
    dirs: [".claude/commands"],
  },
  {
    agent: "Cursor",
    files: [".cursorrules", ".cursor/rules"],
  },
  {
    agent: "GitHub Copilot",
    files: [".github/copilot-instructions.md"],
  },
  {
    agent: "Aider",
    files: [".aider.conf.yml", ".aiderignore"],
  },
  {
    agent: "Generic (all agents)",
    files: ["AGENTS.md", ".agentignore"],
  },
] as const;

/** Keywords that indicate critical build/test/architecture info */
const CRITICAL_INFO_PATTERNS = [
  /\b(pnpm|npm|yarn|make|cargo|go)\s+(install|build|test|run)/i,
  /\b(build|test|lint|format|typecheck)\s*(command|script|step)/i,
  /```\s*(bash|sh|shell|zsh)/i,
  /##\s*(architecture|overview|structure|getting started|setup|build|test)/i,
];

/** Patterns that suggest auto-generated/boilerplate content */
const BOILERPLATE_PATTERNS = [
  /^this project is a\b/im,
  /^this is a\b/im,
  /^welcome to\b/im,
  /^## getting started[ \t]*\n[ \t]*\n[ \t]*## /im,
  /^## table of contents/im,
  /generated by /i,
  /auto-generated/i,
  /do not edit/i,
];

/** Reference document types used for additionality comparison */
const REFERENCE_DOC_PATHS = [
  "README.md",
  "CONTRIBUTING.md",
  "CONTRIBUTING",
  "docs/README.md",
] as const;

/** Config files to include in reference corpus for additionality comparison */
const REFERENCE_CONFIG_PATHS = [
  "tsconfig.json",
  "Makefile",
  "Dockerfile",
  "Cargo.toml",
  "pyproject.toml",
  "setup.cfg",
  "Gemfile",
  "go.mod",
] as const;

/**
 * Additional config file patterns discovered dynamically from the file list.
 * These cover common build/test/workspace configs that vary across ecosystems
 * and would be impractical to enumerate in a static allowlist.
 */
const DYNAMIC_CONFIG_PATTERNS: RegExp[] = [
  /^turbo\.json$/,
  /^pnpm-workspace\.yaml$/,
  /^\.ariscan\.yml$/,
  /^vitest\.config\.[a-z]+$/,
  /^vitest\.workspace\.[a-z]+$/,
  /^jest\.config\.[a-z]+$/,
  /^webpack\.config\.[a-z]+$/,
  /^rollup\.config\.[a-z]+$/,
  /^vite\.config\.[a-z]+$/,
  /^babel\.config\.[a-z]+$/,
  /^\.babelrc$/,
  /^tsconfig\.[a-z.]+\.json$/,
  /^docker-compose\.ya?ml$/,
  /^\.dockerignore$/,
  /^\.nvmrc$/,
  /^\.node-version$/,
  /^\.tool-versions$/,
  /^\.editorconfig$/,
  /^biome\.json$/,
  /^deno\.json[c]?$/,
  /^nx\.json$/,
  /^lerna\.json$/,
  /^rush\.json$/,
];

/** Common source-file extensions for docstring extraction */
const SOURCE_EXTENSIONS = [".ts", ".js", ".py", ".go", ".rs", ".java", ".rb"] as const;

/** Maximum number of source files to scan for leading docstrings.
 *  Set high enough to cover all meaningful source files in most repos
 *  while still bounding worst-case cost in very large monorepos. */
const MAX_SOURCE_FILES_FOR_DOCSTRINGS = 200;

/** CI workflow glob prefixes to gather reference content */
const CI_WORKFLOW_PREFIXES = [".github/workflows/", ".gitlab-ci"] as const;

interface DiscoveredFile {
  path: string;
  size: number;
  lineCount: number;
}

/** Result of additionality analysis for a single context file */
interface AdditionalityResult {
  redundancyPct: number; // 0-100, one decimal
  additionalityPct: number; // 0-100, one decimal
  duplicateLines: Array<{ line: number; text: string; matchedIn: string }>;
  additiveLines: Array<{ line: number; text: string }>;
  methodology: string;
}

/**
 * Flatten a JSON value into plain text lines grouped by top-level key.
 * Each top-level key produces one line containing all nested key-value pairs,
 * ensuring segments are long enough to survive the word-count filter.
 * E.g. { compilerOptions: { target: "ES2022", strict: true } }
 *   → "compilerOptions target ES2022 strict true"
 */
function flattenJsonToText(val: unknown): string[] {
  if (val === null || val === undefined) return [];
  if (typeof val !== "object" || Array.isArray(val)) return [String(val)];
  const lines: string[] = [];
  for (const [topKey, topVal] of Object.entries(val as Record<string, unknown>)) {
    const leaves: string[] = [];
    collectLeaves(topVal, leaves);
    // Group all leaves under the top-level key into a single segment
    lines.push(`${topKey} ${leaves.join(" ")}`);
  }
  return lines;
}

/** Recursively collect leaf key-value pairs as "key value" tokens. */
function collectLeaves(val: unknown, out: string[]): void {
  if (val === null || val === undefined) return;
  if (typeof val !== "object") {
    out.push(String(val));
    return;
  }
  if (Array.isArray(val)) {
    for (const item of val) collectLeaves(item, out);
    return;
  }
  for (const [k, v] of Object.entries(val as Record<string, unknown>)) {
    if (typeof v === "object" && v !== null) {
      out.push(k);
      collectLeaves(v, out);
    } else {
      out.push(`${k} ${String(v)}`);
    }
  }
}

/**
 * Normalize config file content into comparable plain text.
 * JSON files are parsed and flattened into key-value lines.
 * Other structured formats (TOML, YAML, Makefile, Dockerfile, etc.)
 * have structural punctuation stripped to produce comparable tokens.
 */
function normalizeConfigContent(content: string, path: string): string {
  // JSON files: parse and flatten for best results
  if (path.endsWith(".json")) {
    try {
      const parsed: unknown = JSON.parse(content);
      const lines = flattenJsonToText(parsed);
      return lines.length > 0 ? lines.join("\n") : content;
    } catch {
      // Fall through to generic stripping
    }
  }
  // Generic structured config: strip punctuation that hurts Jaccard matching
  return content
    .replace(/[{}[\]"',;()<>]/g, " ")
    .replace(/[^\S\n]+/g, " ")
    .trim();
}

/**
 * Strip HTML tags and comments from text, replacing each with a space to
 * preserve word boundaries. Uses character iteration instead of regex to
 * avoid CodeQL incomplete-multi-character-sanitization false positives.
 */
function stripHtmlTags(text: string): string {
  let result = "";
  let i = 0;
  while (i < text.length) {
    if (text[i] === "<") {
      const close = text.indexOf(">", i + 1);
      if (close !== -1) {
        result += " ";
        i = close + 1;
      } else {
        // No closing > — skip the lone <
        i++;
      }
    } else {
      result += text[i];
      i++;
    }
  }
  return result;
}

/**
 * Strip markdown formatting to extract plain text for comparison.
 * Removes code fences, headings markers, links, images, bold/italic markers.
 */
function normalizeForComparison(text: string): string {
  let normalized = text
    // Strip fenced code block delimiters but keep content (commands/config may be duplicated)
    .replace(/```[^\n]*\n?/g, "")
    // Strip inline code backticks but keep content
    .replace(/`([^`]+)`/g, "$1")
    // Remove markdown headings markers
    .replace(/^#{1,6}\s+/gm, "")
    // Remove link syntax but keep text: [text](url) → text
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    // Remove image syntax
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, "")
    // Remove bold/italic marker characters (*, _) left after other stripping
    .replace(/\*+/g, "")
    .replace(/_+/g, "");

  // Strip HTML tags/comments — replaces <tag> with space, preserves enclosed text
  normalized = stripHtmlTags(normalized);

  return (
    normalized
      // Remove list-item markers (-, *, numbered) but keep the text on its own line
      .replace(/^\s*[-*]\s+/gm, "")
      .replace(/^\s*\d+[.)]\s+/gm, "")
      // Collapse horizontal whitespace (preserve newlines for segmentation)
      .replace(/[^\S\n]+/g, " ")
      .trim()
  );
}

/**
 * Extract the leading comment/docstring block from a source file.
 * Returns the text of the first block comment or consecutive line comments
 * at the top of the file (after any shebang or blank lines).
 */
function extractLeadingDocstring(content: string): string | null {
  const lines = content.split("\n");
  let i = 0;
  // Skip shebang and blank lines
  while (i < lines.length) {
    const line = lines[i] as string;
    if (line.trim() !== "" && !line.startsWith("#!")) break;
    i++;
  }
  if (i >= lines.length) return null;

  const firstLine = (lines[i] as string).trimStart();

  // Block comment: /** ... */ or /* ... */
  if (firstLine.startsWith("/**") || firstLine.startsWith("/*")) {
    const blockLines: string[] = [];
    const startIdx = i;
    for (; i < lines.length; i++) {
      const line = lines[i] as string;
      blockLines.push(line);
      if (line.includes("*/") && i > startIdx) break;
      if (i === startIdx && line.trimEnd().endsWith("*/")) break;
    }
    return blockLines.join("\n");
  }
  // Python triple-quote docstrings
  if (firstLine.startsWith('"""') || firstLine.startsWith("'''")) {
    const delim = firstLine.slice(0, 3);
    const currentLine = lines[i] as string;
    const blockLines: string[] = [currentLine];
    if (firstLine.indexOf(delim, 3) > 3) return firstLine; // single-line docstring
    for (i++; i < lines.length; i++) {
      const line = lines[i] as string;
      blockLines.push(line);
      if (line.includes(delim)) break;
    }
    return blockLines.join("\n");
  }
  // Consecutive line comments: //, #, --
  const commentPrefixes = ["//", "#", "--"];
  const prefix = commentPrefixes.find((p) => firstLine.startsWith(p));
  if (prefix) {
    const commentLines: string[] = [];
    for (; i < lines.length; i++) {
      const line = lines[i] as string;
      if (line.trimStart().startsWith(prefix)) {
        commentLines.push(line);
      } else {
        break;
      }
    }
    if (commentLines.length >= 2) return commentLines.join("\n");
  }
  return null;
}

/**
 * Detect whether a segment looks like a CLI command or config/assignment
 * line rather than prose.  Uses syntax-based heuristics so that commands
 * and config from any ecosystem are recognized without a tool-name whitelist.
 *
 * A segment is command-or-config-like if it:
 *  - Is a config/assignment line: `key: value`, `key=value`, YAML `uses:`/`run:` lines
 *  - Starts with an executable token followed by flags, paths, or sub-commands
 *  - Is a short (2-4 word) all-lowercase segment with no sentence punctuation
 */
function isCommandLike(segment: string): boolean {
  const trimmed = segment.trim();
  const words = trimmed.split(/\s+/);
  if (words.length < 2) return false;

  // --- Config / assignment syntax ---
  // Matches `key: value`, `key=value`, `KEY=value` patterns
  // e.g. "test: pnpm test", "build: turbo build", "uses: actions/checkout@v4",
  //      "NODE_ENV=production", "run: npm ci"
  const first = words[0] ?? "";
  if (/^[a-zA-Z][a-zA-Z0-9_.-]*[:=]$/.test(first) || /^[a-zA-Z][a-zA-Z0-9_.-]*=/.test(first)) {
    return true;
  }
  // Also catch `key=value` as a single token (no space after =)
  if (/^[a-zA-Z][a-zA-Z0-9_.-]*=.+/.test(trimmed) && words.length <= 4) {
    return true;
  }

  // --- Path-like launcher syntax ---
  // Matches ./foo, ../foo, bin/foo, scripts/foo, vendor/bin/foo, etc.
  // These are common in READMEs and CI docs (e.g. ./gradlew test, bin/rails test,
  // scripts/build --prod, ./scripts/check.sh)
  if (/^\.{0,2}\//.test(first) || /^[a-zA-Z][a-zA-Z0-9._-]*\//.test(first)) {
    return true;
  }

  // --- Executable-first command syntax ---
  // Executable names are lowercase, may contain hyphens or dots (e.g. docker-compose, node.js)
  if (!/^[a-z][a-z0-9._-]*$/i.test(first)) return false;
  // Reject if the first word looks like a common English article/pronoun/verb
  const PROSE_STARTERS = new Set([
    "the",
    "this",
    "that",
    "these",
    "those",
    "a",
    "an",
    "it",
    "its",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "if",
    "for",
    "but",
    "and",
    "or",
    "so",
    "we",
    "our",
    "you",
    "your",
    "can",
    "will",
    "may",
    "has",
    "have",
    "had",
    "do",
    "does",
    "did",
    "not",
    "no",
    "all",
    "each",
    "every",
    "some",
    "any",
    "when",
    "where",
    "how",
    "what",
    "which",
    "who",
  ]);
  if (PROSE_STARTERS.has(first.toLowerCase())) return false;

  // Check if remaining tokens contain flag-like (--flag, -x) or path-like patterns
  const rest = words.slice(1);
  const hasFlag = rest.some((w) => /^-{1,2}[a-zA-Z]/.test(w));
  const hasPath = rest.some((w) => /[/.\\]/.test(w));
  if (hasFlag || hasPath) return true;

  // Short all-lowercase segments with no sentence punctuation: likely commands
  // Allow colons in this check since config lines are handled above
  if (words.length <= 4 && trimmed === trimmed.toLowerCase() && !/[,;!?]/.test(trimmed)) {
    return true;
  }

  return false;
}

/**
 * Split text into meaningful sentences/segments for comparison.
 * Splits on sentence-ending periods, newlines, and list boundaries.
 * Uses a lower word threshold for command-like segments so that short
 * operational guidance (e.g. `pnpm install`, `npm ci`) participates
 * in redundancy scoring.
 */
function splitSegments(text: string): string[] {
  // Split on newlines first, then on sentence-ending periods within each line
  const raw: string[] = [];
  for (const line of text.split("\n")) {
    // Split on periods that end a sentence (followed by space or end of string)
    const parts = line.split(/\.(?:\s|$)/).map((s) => s.trim());
    for (const part of parts) {
      if (part.length > 0) raw.push(part);
    }
  }
  // Apply different word-count thresholds:
  // - Command-like segments (CLI invocations, config lines): >= 2 words
  // - Prose segments: >= 5 words (avoids false positives on short phrases)
  return raw.filter((s) => {
    const wordCount = s.split(/\s+/).length;
    if (isCommandLike(s)) return wordCount >= 2;
    return wordCount >= 5;
  });
}

/**
 * Compute Jaccard similarity between two word sets.
 * Returns value 0-1.
 */
function jaccardSimilarity(a: string, b: string): number {
  const wordsA = new Set(a.toLowerCase().split(/\s+/));
  const wordsB = new Set(b.toLowerCase().split(/\s+/));
  let intersection = 0;
  for (const w of wordsA) {
    if (wordsB.has(w)) intersection++;
  }
  const union = wordsA.size + wordsB.size - intersection;
  if (union === 0) return 0;
  return intersection / union;
}

/**
 * Compute additionality for a context file against reference documents.
 * Uses sentence-level Jaccard similarity to identify duplicated content.
 */
function computeAdditionality(
  contextContent: string,
  contextPath: string,
  referenceDocs: Array<{ path: string; content: string }>,
): AdditionalityResult {
  const normalizedContext = normalizeForComparison(contextContent);
  const contextSegments = splitSegments(normalizedContext);

  // Pre-compute reference segments
  const refSegments: Array<{ segment: string; path: string }> = [];
  for (const doc of referenceDocs) {
    const normalized = normalizeForComparison(doc.content);
    for (const seg of splitSegments(normalized)) {
      refSegments.push({ segment: seg, path: doc.path });
    }
  }

  // Map original lines to their comparison status
  const lines = contextContent.split("\n");
  const duplicateLines: AdditionalityResult["duplicateLines"] = [];
  const additiveLines: AdditionalityResult["additiveLines"] = [];

  // Track per-segment match status
  let matchedSegments = 0;
  const totalSegments = contextSegments.length;

  const SIMILARITY_THRESHOLD = 0.6;

  for (const segment of contextSegments) {
    let bestMatch = 0;
    let bestMatchPath = "";
    for (const ref of refSegments) {
      const sim = jaccardSimilarity(segment, ref.segment);
      if (sim > bestMatch) {
        bestMatch = sim;
        bestMatchPath = ref.path;
      }
    }
    if (bestMatch >= SIMILARITY_THRESHOLD) {
      matchedSegments++;
      // Find the original line that best corresponds to this segment
      // Use Jaccard similarity (same as segment comparison) to handle formatting differences
      let bestLineScore = 0;
      let bestLineIdx = -1;
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i] ?? "";
        const normalizedLine = line
          .toLowerCase()
          .replace(/[-#*_`()[\].:>]/g, "")
          .trim();
        const lineWordCount = normalizedLine.split(/\s+/).length;
        const minWords = isCommandLike(normalizedLine) ? 2 : 3;
        if (lineWordCount < minWords) continue;
        const sim = jaccardSimilarity(segment, normalizedLine);
        if (sim > bestLineScore) {
          bestLineScore = sim;
          bestLineIdx = i;
        }
      }
      if (bestLineIdx >= 0 && bestLineScore >= 0.4) {
        if (!duplicateLines.some((d) => d.line === bestLineIdx + 1)) {
          duplicateLines.push({
            line: bestLineIdx + 1,
            text: (lines[bestLineIdx] ?? "").trim(),
            matchedIn: bestMatchPath,
          });
        }
      }
    }
  }

  // Identify additive lines (non-empty, non-duplicate, meaningful)
  const dupLineNums = new Set(duplicateLines.map((d) => d.line));
  for (let i = 0; i < lines.length; i++) {
    const trimmed = (lines[i] ?? "").trim();
    if (trimmed.length >= 10 && !dupLineNums.has(i + 1)) {
      // Skip pure markdown formatting lines
      if (!/^(#{1,6}\s*$|```|---|\*\*\*|___|\|)/.test(trimmed)) {
        additiveLines.push({ line: i + 1, text: trimmed });
      }
    }
  }

  // When no comparable segments exist, report -1 to signal indeterminate result
  const redundancyPct =
    totalSegments > 0 ? Math.round((matchedSegments / totalSegments) * 1000) / 10 : -1;
  const additionalityPct = redundancyPct >= 0 ? Math.round((100 - redundancyPct) * 10) / 10 : -1;

  const methodology = [
    `Sentence-level Jaccard similarity (threshold ≥ ${SIMILARITY_THRESHOLD}).`,
    `Compared ${totalSegments} segments from ${contextPath}`,
    `against ${refSegments.length} segments from ${referenceDocs.map((d) => d.path).join(", ")}.`,
    `${matchedSegments}/${totalSegments} segments matched as duplicative.`,
  ].join(" ");

  return { redundancyPct, additionalityPct, duplicateLines, additiveLines, methodology };
}

/**
 * Check if critical information is front-loaded in the first 20% of a file.
 * Returns true if critical info is found only in the bottom 80%.
 */
function hasBuriedCriticalInfo(content: string): boolean {
  const lines = content.split("\n");
  const cutoff = Math.max(1, Math.ceil(lines.length * 0.2));
  const topSection = lines.slice(0, cutoff).join("\n");
  const bottomSection = lines.slice(cutoff).join("\n");

  // Check if critical info exists in bottom but NOT in top
  const topHasCritical = CRITICAL_INFO_PATTERNS.some((p) => p.test(topSection));
  const bottomHasCritical = CRITICAL_INFO_PATTERNS.some((p) => p.test(bottomSection));

  return !topHasCritical && bottomHasCritical;
}

/**
 * Extract file/directory path references from content.
 * Looks for patterns like `path/to/file.ts`, `./src/`, `packages/foo/`, etc.
 */
function extractReferencedPaths(content: string): string[] {
  const pathPattern = /(?:^|[\s`"])((?:\.\.?\/)?[a-zA-Z0-9_-]+\/[a-zA-Z0-9_./-]*)/gm;
  const paths: string[] = [];
  let match: RegExpExecArray | null;
  while ((match = pathPattern.exec(content)) !== null) {
    const p = match[1]?.replace(/^\.\//, "");
    // Filter out common non-path matches
    if (p && !p.startsWith("http") && !p.startsWith("//")) {
      paths.push(p);
    }
  }
  return paths;
}

/**
 * Check if content appears to be auto-generated boilerplate without project specifics.
 */
function isLikelyBoilerplate(content: string, repoFiles: readonly string[]): boolean {
  // Check for boilerplate patterns
  const hasBoilerplateMarkers = BOILERPLATE_PATTERNS.some((p) => p.test(content));

  // Check if content references any actual repo files/directories
  const repoFilenames = new Set<string>();
  for (const f of repoFiles) {
    // Add both full path and filename parts
    const parts = f.split("/");
    for (const part of parts) {
      if (part && part.length > 2 && !part.startsWith(".")) {
        repoFilenames.add(part);
      }
    }
  }

  // Count project-specific references
  let specificRefs = 0;
  for (const name of repoFilenames) {
    if (content.includes(name)) {
      specificRefs++;
    }
  }

  // Consider it boilerplate if it has boilerplate markers AND few project-specific references
  return hasBoilerplateMarkers && specificRefs < 2;
}

export const contextQualityAnalyzer: PillarAnalyzer = {
  pillar: PILLAR,
  name: PILLAR_NAMES[PILLAR],
  version: "0.2.0",

  async supports(): Promise<boolean> {
    return true;
  },

  async analyze(context: RepoContext) {
    const findings: Finding[] = [];
    let score = 20; // Baseline: no context files = 20%

    const discoveredFiles: DiscoveredFile[] = [];
    const foundContextFiles: string[] = [];

    // Check standard context files
    for (const cf of CONTEXT_FILES) {
      const exists = await context.fileExists(cf);
      if (exists) {
        foundContextFiles.push(cf);
        const content = await context.readFile(cf);
        if (content !== null) {
          discoveredFiles.push({
            path: cf,
            size: content.length,
            lineCount: content.split("\n").length,
          });
        }
      }
    }

    // Check directory patterns
    for (const dir of CONTEXT_DIRS) {
      const hasFiles = context.files.some((f) => f.startsWith(dir + "/"));
      if (hasFiles) {
        const dirLabel = dir + "/";
        foundContextFiles.push(dirLabel);
        discoveredFiles.push({ path: dirLabel, size: 0, lineCount: 0 });
      }
    }

    // Discover nested AGENTS.md files for monorepos
    const nestedAgentsFiles = context.files.filter(
      (f) => f !== "AGENTS.md" && f.endsWith("/AGENTS.md"),
    );
    for (const nestedFile of nestedAgentsFiles) {
      if (!foundContextFiles.includes(nestedFile)) {
        foundContextFiles.push(nestedFile);
        const content = await context.readFile(nestedFile);
        if (content !== null) {
          discoveredFiles.push({
            path: nestedFile,
            size: content.length,
            lineCount: content.split("\n").length,
          });
        }
      }
    }

    if (foundContextFiles.length === 0) {
      findings.push({
        code: "ARI-CTX-001",
        severity: "high",
        pillar: PILLAR,
        message: "No agent context files found (AGENTS.md, CLAUDE.md, .cursorrules, etc.)",
        confidence: "high",
        remediation: {
          action: "create-file",
          path: "AGENTS.md",
          description:
            "Create an AGENTS.md file with project-specific context for AI coding agents",
          estimatedImpact: "+12 points composite",
          confidence: "high",
        },
        evidence: {
          paper: "Lulla et al., 2026",
          finding: "Quality AGENTS.md reduces agent time 28.6%, tokens 16.6%",
          confidence: "high",
        },
      });
    } else {
      // Base score boost for having context files
      score += 15 * Math.min(foundContextFiles.length, 3);

      // Check AGENTS.md quality if it exists
      if (foundContextFiles.includes("AGENTS.md")) {
        const content = await context.readFile("AGENTS.md");
        if (content) {
          const lines = content.split("\n").length;
          const hasHeadings = /^#+\s/m.test(content);
          const hasCodeBlocks = /```/.test(content);
          const hasDontStatements = /\b(don't|do not|never|avoid)\b/i.test(content);

          if (lines < 10) {
            findings.push({
              code: "ARI-CTX-002",
              severity: "medium",
              pillar: PILLAR,
              message:
                "AGENTS.md is too short (< 10 lines). Effective context files provide detailed project-specific guidance.",
              confidence: "medium",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description:
                  "Expand AGENTS.md with architecture overview, conventions, and common pitfalls",
                confidence: "high",
              },
            });
          } else {
            score += 10;
          }

          if (hasHeadings) score += 5;
          if (hasCodeBlocks) score += 5;
          if (hasDontStatements) score += 5; // Negative instructions are valuable

          // Front-loading check (ARI-CTX-005) for AGENTS.md
          if (lines >= 10 && hasBuriedCriticalInfo(content)) {
            findings.push({
              code: "ARI-CTX-005",
              severity: "medium",
              pillar: PILLAR,
              message:
                "AGENTS.md has critical info (build commands, architecture) buried below the first 20% of the file. Front-load important context for better agent performance.",
              confidence: "medium",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description:
                  "Move build commands, test commands, and architecture overview to the top of AGENTS.md",
                confidence: "medium",
              },
            });
            score -= 5;
          }

          // Staleness detection (ARI-CTX-006)
          const referencedPaths = extractReferencedPaths(content);
          const fileSet = new Set(context.files);
          const stalePaths: string[] = [];
          for (const rp of referencedPaths) {
            // Check if the referenced path exists as a file or as a directory prefix
            const rpClean = rp.replace(/\/$/, "");
            const existsAsFile = fileSet.has(rpClean);
            const existsAsDir = context.files.some((f) => f.startsWith(rpClean + "/"));
            if (!existsAsFile && !existsAsDir) {
              stalePaths.push(rp);
            }
          }
          if (stalePaths.length > 0) {
            findings.push({
              code: "ARI-CTX-006",
              severity: "low",
              pillar: PILLAR,
              message: `AGENTS.md references ${stalePaths.length} path(s) not found in the repo: ${stalePaths.slice(0, 3).join(", ")}${stalePaths.length > 3 ? "..." : ""}. Content may be stale.`,
              confidence: "medium",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description:
                  "Review and update AGENTS.md to remove or fix references to non-existent paths",
                confidence: "low",
              },
            });
            score -= 3;
          }

          // Boilerplate detection (ARI-CTX-007)
          if (isLikelyBoilerplate(content, context.files)) {
            findings.push({
              code: "ARI-CTX-007",
              severity: "medium",
              pillar: PILLAR,
              message:
                "AGENTS.md appears to contain auto-generated or boilerplate content without project-specific details.",
              confidence: "low",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description:
                  "Replace boilerplate content with project-specific architecture, conventions, and build instructions",
                confidence: "medium",
              },
            });
            score -= 10;
          }

          // Conciseness check (ARI-CTX-008)
          if (lines > 500) {
            const codeBlockMatches = content.match(/```/g);
            const codeBlockCount = codeBlockMatches ? Math.floor(codeBlockMatches.length / 2) : 0;
            // Expect roughly 1 code block per 50 lines for well-structured docs
            const expectedBlocks = Math.floor(lines / 50);
            if (codeBlockCount < expectedBlocks / 2) {
              findings.push({
                code: "ARI-CTX-008",
                severity: "low",
                pillar: PILLAR,
                message: `AGENTS.md is very long (${lines} lines) without proportional code examples. Verbose context files can reduce agent efficiency.`,
                confidence: "low",
                remediation: {
                  action: "modify-config",
                  path: "AGENTS.md",
                  description: "Condense AGENTS.md or add more code examples to justify the length",
                  confidence: "medium",
                },
              });
              score -= 5;
            }
          }
        }
      }

      // Front-loading check for CLAUDE.md
      if (foundContextFiles.includes("CLAUDE.md")) {
        const claudeContent = await context.readFile("CLAUDE.md");
        if (claudeContent) {
          const claudeLines = claudeContent.split("\n").length;
          if (claudeLines >= 10 && hasBuriedCriticalInfo(claudeContent)) {
            findings.push({
              code: "ARI-CTX-005",
              severity: "medium",
              pillar: PILLAR,
              message:
                "CLAUDE.md has critical info (build commands, architecture) buried below the first 20% of the file. Front-load important context for better agent performance.",
              confidence: "medium",
              remediation: {
                action: "modify-config",
                path: "CLAUDE.md",
                description:
                  "Move build commands, test commands, and architecture overview to the top of CLAUDE.md",
                confidence: "medium",
              },
            });
            score -= 5;
          }
        }
      }

      // Check for .agentignore
      if (foundContextFiles.includes(".agentignore")) {
        score += 10;
      } else {
        findings.push({
          code: "ARI-CTX-003",
          severity: "low",
          pillar: PILLAR,
          message:
            "No .agentignore file found. This file helps agents exclude irrelevant files from context.",
          confidence: "high",
          remediation: {
            action: "create-file",
            path: ".agentignore",
            description:
              "Create .agentignore to exclude generated files, vendor code, and binaries from agent context",
            confidence: "medium",
          },
        });
      }
    }

    // --- ARI-CTX-009: Non-parsable context file warnings ---
    // Validate parse status for structured context files (JSON, YAML)
    const nonParsableFiles: Array<{ path: string; reason: string }> = [];
    for (const cf of foundContextFiles) {
      const content = await context.readFile(cf);
      if (content === null) continue;

      if (cf.endsWith(".json")) {
        try {
          JSON.parse(content);
        } catch {
          nonParsableFiles.push({ path: cf, reason: "invalid JSON" });
        }
      } else if (cf.endsWith(".yml") || cf.endsWith(".yaml")) {
        const trimmed = content.trim();
        if (trimmed.length === 0) {
          nonParsableFiles.push({ path: cf, reason: "empty YAML file" });
        } else if (/^\t+ /m.test(trimmed) || /^ +\t/m.test(trimmed)) {
          nonParsableFiles.push({ path: cf, reason: "mixed tabs and spaces in YAML" });
        }
      }

      // Check for completely empty files (any type)
      if (content.trim().length === 0 && !cf.endsWith(".yml") && !cf.endsWith(".yaml")) {
        nonParsableFiles.push({ path: cf, reason: "empty file" });
      }
    }

    if (nonParsableFiles.length > 0) {
      score -= 5 * nonParsableFiles.length;
      const details = nonParsableFiles
        .slice(0, 3)
        .map((f) => `${f.path} (${f.reason})`)
        .join(", ");
      findings.push({
        code: "ARI-CTX-009",
        severity: "high",
        pillar: PILLAR,
        message: `${nonParsableFiles.length} context file(s) failed parse validation: ${details}${nonParsableFiles.length > 3 ? ` and ${nonParsableFiles.length - 3} more` : ""}`,
        confidence: "high",
        remediation: {
          action: "modify-config",
          description:
            "Fix parse errors in context files. Invalid JSON or malformed YAML will prevent agents from reading configuration correctly.",
          confidence: "high",
        },
      });
    }

    // --- ARI-CTX-010: Cross-agent compatibility report ---
    const coveredAgents: string[] = [];
    const uncoveredAgents: string[] = [];

    for (const mapping of AGENT_MAPPINGS) {
      const hasFile = mapping.files.some((f) => foundContextFiles.includes(f));
      const hasDir = mapping.dirs?.some((d) => foundContextFiles.includes(d + "/")) ?? false;

      if (hasFile || hasDir) {
        coveredAgents.push(mapping.agent);
      } else {
        uncoveredAgents.push(mapping.agent);
      }
    }

    if (uncoveredAgents.length > 0 && foundContextFiles.length > 0) {
      findings.push({
        code: "ARI-CTX-010",
        severity: "info",
        pillar: PILLAR,
        message: `Agent context coverage: ${coveredAgents.length}/${AGENT_MAPPINGS.length} agents covered. Missing: ${uncoveredAgents.join(", ")}.`,
        confidence: "high",
        remediation: {
          action: "create-file",
          description: `Add context files for uncovered agents: ${uncoveredAgents.join(", ")}. Use AGENTS.md for vendor-neutral context that all agents can read.`,
          confidence: "medium",
        },
      });
    } else if (foundContextFiles.length === 0) {
      findings.push({
        code: "ARI-CTX-010",
        severity: "medium",
        pillar: PILLAR,
        message: `Agent context coverage: 0/${AGENT_MAPPINGS.length} agents covered. No agent has dedicated context files.`,
        confidence: "high",
        remediation: {
          action: "create-file",
          path: "AGENTS.md",
          description:
            "Start with AGENTS.md for vendor-neutral context, then add agent-specific files (CLAUDE.md, .cursorrules, etc.) as needed.",
          confidence: "high",
        },
      });
    }

    // Check README quality as context baseline
    const readme = await context.readFile("README.md");
    if (readme) {
      const readmeLines = readme.split("\n").length;
      if (readmeLines > 20) score += 5;
    } else {
      findings.push({
        code: "ARI-CTX-004",
        severity: "medium",
        pillar: PILLAR,
        message: "No README.md found. README serves as baseline context for all agents.",
        confidence: "high",
        remediation: {
          action: "create-file",
          path: "README.md",
          description:
            "Create a README.md with project overview, setup instructions, and architecture summary",
          confidence: "high",
        },
      });
    }

    // --- Additionality analysis (P1.04) ---
    // Gather reference documents for comparison
    const referenceDocs: Array<{ path: string; content: string }> = [];
    for (const refPath of REFERENCE_DOC_PATHS) {
      const content = await context.readFile(refPath);
      if (content) {
        referenceDocs.push({ path: refPath, content });
      }
    }
    // Gather CI workflow files
    for (const prefix of CI_WORKFLOW_PREFIXES) {
      for (const f of context.files) {
        if (f.startsWith(prefix) && (f.endsWith(".yml") || f.endsWith(".yaml"))) {
          const content = await context.readFile(f);
          if (content) {
            referenceDocs.push({ path: f, content });
          }
        }
      }
    }
    // Include package.json scripts section as reference
    const pkgJson = await context.readJson<{
      description?: string;
      scripts?: Record<string, string>;
    }>("package.json");
    if (pkgJson) {
      const parts: string[] = [];
      if (pkgJson.description) parts.push(pkgJson.description);
      if (pkgJson.scripts) {
        for (const [key, val] of Object.entries(pkgJson.scripts)) {
          parts.push(`${key}: ${val}`);
        }
      }
      if (parts.length > 0) {
        referenceDocs.push({ path: "package.json", content: parts.join("\n") });
      }
    }
    // Include config files in reference corpus (normalized for comparison)
    for (const cfgPath of REFERENCE_CONFIG_PATHS) {
      const content = await context.readFile(cfgPath);
      if (content) {
        referenceDocs.push({ path: cfgPath, content: normalizeConfigContent(content, cfgPath) });
      }
    }
    // Also include eslint/prettier config files found by pattern (including nested paths)
    for (const f of context.files) {
      const bn = f.includes("/") ? f.slice(f.lastIndexOf("/") + 1) : f;
      if (
        (bn.match(/^\.eslintrc(\.[a-z]+)?$/) ||
          bn.match(/^\.prettierrc(\.[a-z]+)?$/) ||
          bn === "eslint.config.js" ||
          bn === "eslint.config.mjs" ||
          bn === "prettier.config.js" ||
          bn === "prettier.config.mjs") &&
        !referenceDocs.some((d) => d.path === f) &&
        !/(?:^|\/)(node_modules|dist|build)\//.test(f)
      ) {
        const content = await context.readFile(f);
        if (content) {
          referenceDocs.push({ path: f, content: normalizeConfigContent(content, f) });
        }
      }
    }
    // Include dynamically-discovered config files matching common patterns
    // Match on basename so monorepo nested configs (e.g. packages/foo/vitest.config.ts) are included
    for (const f of context.files) {
      if (referenceDocs.some((d) => d.path === f)) continue;
      // Skip files inside node_modules, dist, or build directories
      if (/(?:^|\/)(node_modules|dist|build|\.next|\.nuxt)\//.test(f)) continue;
      const basename = f.includes("/") ? f.slice(f.lastIndexOf("/") + 1) : f;
      if (DYNAMIC_CONFIG_PATTERNS.some((p) => p.test(basename))) {
        const content = await context.readFile(f);
        if (content) {
          referenceDocs.push({ path: f, content: normalizeConfigContent(content, f) });
        }
      }
    }

    // Extract leading docstrings/comments from source files
    let docstringCount = 0;
    for (const f of context.files) {
      if (docstringCount >= MAX_SOURCE_FILES_FOR_DOCSTRINGS) break;
      if (!SOURCE_EXTENSIONS.some((ext) => f.endsWith(ext))) continue;
      // Skip test files and generated files
      if (f.includes("__tests__") || f.includes(".test.") || f.includes(".spec.")) continue;
      if (f.includes("node_modules/") || f.includes("dist/") || f.includes("build/")) continue;
      const content = await context.readFile(f);
      if (!content) continue;
      const docstring = extractLeadingDocstring(content);
      if (docstring && docstring.length > 50) {
        referenceDocs.push({ path: f, content: docstring });
        docstringCount++;
      }
    }

    // Run additionality analysis on text-based context files
    const TEXT_CONTEXT_FILES = [
      "AGENTS.md",
      "CLAUDE.md",
      ".cursorrules",
      ".cursor/rules",
      ".github/copilot-instructions.md",
    ];
    const additionalityResults: Array<{
      path: string;
      result: AdditionalityResult;
    }> = [];

    if (referenceDocs.length > 0) {
      for (const cf of foundContextFiles) {
        if (!TEXT_CONTEXT_FILES.includes(cf) && !cf.endsWith("/AGENTS.md")) continue;
        const content = await context.readFile(cf);
        if (!content || content.trim().length === 0) continue;

        // For nested AGENTS.md files, augment the corpus with package-local docs
        let effectiveRefDocs = referenceDocs;
        if (cf.endsWith("/AGENTS.md") && cf !== "AGENTS.md") {
          // Walk upward from the AGENTS.md path to find the nearest package root.
          // Prefer package.json (strongest signal) over README-bearing directories,
          // so that layouts like packages/foo/docs/AGENTS.md resolve to packages/foo/
          // even when packages/foo/docs/README.md exists.
          const parts = cf.split("/");
          parts.pop(); // remove "AGENTS.md"
          let pkgDir = parts.join("/") + "/"; // start from immediate parent

          // Pass 1: walk upward looking for a directory with package.json
          const partsForPkg = [...parts];
          let foundPkgJson = false;
          while (partsForPkg.length > 0) {
            const candidate = partsForPkg.join("/") + "/";
            const hasPkgJson = context.files.some((f) => {
              if (!f.startsWith(candidate)) return false;
              const rest = f.slice(candidate.length);
              return rest === "package.json";
            });
            if (hasPkgJson) {
              pkgDir = candidate;
              foundPkgJson = true;
              break;
            }
            partsForPkg.pop();
          }

          // Pass 2 (fallback): if no package.json found, look for README/CONTRIBUTING
          if (!foundPkgJson) {
            const partsForReadme = [...parts];
            while (partsForReadme.length > 0) {
              const candidate = partsForReadme.join("/") + "/";
              const hasBoundary = context.files.some((f) => {
                if (!f.startsWith(candidate)) return false;
                const rest = f.slice(candidate.length);
                if (rest.includes("/")) return false;
                const upper = rest.toUpperCase();
                return upper.startsWith("README") || upper.startsWith("CONTRIBUTING");
              });
              if (hasBoundary) {
                pkgDir = candidate;
                break;
              }
              partsForReadme.pop();
            }
          }
          const localDocs: Array<{ path: string; content: string }> = [];
          // Gather README* and CONTRIBUTING* files from the package root
          for (const f of context.files) {
            if (!f.startsWith(pkgDir)) continue;
            // Only direct children (no further nesting)
            const rest = f.slice(pkgDir.length);
            if (rest.includes("/")) continue;
            const upper = rest.toUpperCase();
            if (
              (upper.startsWith("README") || upper.startsWith("CONTRIBUTING")) &&
              !referenceDocs.some((d) => d.path === f)
            ) {
              const localContent = await context.readFile(f);
              if (localContent) {
                localDocs.push({ path: f, content: localContent });
              }
            }
          }
          // Gather package.json description/scripts from the package root
          const localPkgPath = `${pkgDir}package.json`;
          if (!referenceDocs.some((d) => d.path === localPkgPath)) {
            const localPkg = await context.readJson<{
              description?: string;
              scripts?: Record<string, string>;
            }>(localPkgPath);
            if (localPkg) {
              const parts: string[] = [];
              if (localPkg.description) parts.push(localPkg.description);
              if (localPkg.scripts) {
                for (const [key, val] of Object.entries(localPkg.scripts)) {
                  parts.push(`${key}: ${val}`);
                }
              }
              if (parts.length > 0) {
                localDocs.push({ path: localPkgPath, content: parts.join("\n") });
              }
            }
          }
          if (localDocs.length > 0) {
            effectiveRefDocs = [...referenceDocs, ...localDocs];
          }
        }

        const result = computeAdditionality(content, cf, effectiveRefDocs);
        additionalityResults.push({ path: cf, result });

        // Skip scoring when no comparable segments were analyzed (indeterminate)
        if (result.redundancyPct < 0) {
          // No segments to compare — do not award bonus or apply penalty
        } else if (result.redundancyPct > 50) {
          // ARI-CTX-011: High redundancy
          const topDuplicates = result.duplicateLines
            .slice(0, 3)
            .map((d) => `L${d.line}: "${d.text}" (similar to ${d.matchedIn})`)
            .join("; ");
          const topAdditive = result.additiveLines
            .slice(0, 3)
            .map((a) => `L${a.line}: "${a.text}"`)
            .join("; ");

          findings.push({
            code: "ARI-CTX-011",
            severity: result.redundancyPct > 70 ? "medium" : "low",
            pillar: PILLAR,
            file: cf,
            message: [
              `${cf} has ${result.redundancyPct.toFixed(1)}% content redundancy with existing repo documentation.`,
              result.methodology,
              topDuplicates ? `Duplicative: ${topDuplicates}.` : "",
              topAdditive ? `Additive: ${topAdditive}.` : "",
            ]
              .filter(Boolean)
              .join(" "),
            confidence: "medium",
            remediation: {
              action: "modify-config",
              path: cf,
              description:
                "Remove content that duplicates README, CONTRIBUTING, or CI config. Focus on project-specific guidance that agents cannot discover through file traversal.",
              estimatedImpact: "+5-10 points composite",
              confidence: "medium",
            },
            evidence: {
              paper: "Gloaguen et al., 2026",
              finding:
                "LLM-generated context files that duplicate README decrease agent success by 2-3% while increasing inference cost by 20%+",
              confidence: "high",
            },
          });

          // Score deduction based on redundancy level
          if (result.redundancyPct > 70) {
            score -= 10;
          } else {
            score -= 5;
          }
        } else if (result.redundancyPct > 30) {
          // ARI-CTX-011: Moderate redundancy — emit info-level finding with deduction
          findings.push({
            code: "ARI-CTX-011",
            severity: "info",
            pillar: PILLAR,
            file: cf,
            message: [
              `${cf} has ${result.redundancyPct.toFixed(1)}% content redundancy with existing repo documentation.`,
              result.methodology,
              "Consider reducing overlap with README or CONTRIBUTING to improve additionality.",
            ].join(" "),
            confidence: "low",
            remediation: {
              action: "modify-config",
              path: cf,
              description:
                "Review content that overlaps with README, CONTRIBUTING, or CI config. Remove duplicated sections and focus on project-specific guidance.",
              confidence: "low",
            },
          });
          score -= 3;
        }

        // Additionality bonus for high-quality context (only when measurable)
        if (result.additionalityPct > 80) {
          score += 5;
        }

        // ARI-CTX-012: LLM-generated file duplicating README
        if (result.redundancyPct > 70 && content && isLikelyBoilerplate(content, context.files)) {
          findings.push({
            code: "ARI-CTX-012",
            severity: "high",
            pillar: PILLAR,
            file: cf,
            message: `${cf} appears to be LLM-generated content that duplicates existing documentation (${result.redundancyPct.toFixed(1)}% redundancy). Auto-generated context files hurt agent performance.`,
            confidence: "medium",
            remediation: {
              action: "modify-config",
              path: cf,
              description:
                "Replace auto-generated content with hand-written, project-specific context. Focus on architecture decisions, conventions, and pitfalls that are not documented elsewhere.",
              estimatedImpact: "+10-15 points composite",
              confidence: "high",
            },
            evidence: {
              paper: "Gloaguen et al., 2026",
              finding:
                "LLM-generated files decrease agent success by 2-3%, human-written files improve by ~4% on niche repos",
              confidence: "high",
            },
          });
          score -= 10; // Additional penalty for LLM-generated duplicate
        }
      }
    }

    // Build summary with file metadata and additionality
    let summary: string;
    if (discoveredFiles.length > 0) {
      const fileDetails = discoveredFiles
        .map((f) =>
          f.size > 0
            ? `${f.path} (${f.lineCount} lines, ${f.size} bytes)`
            : `${f.path} (directory)`,
        )
        .join(", ");
      summary = `Found ${foundContextFiles.length} context file(s): ${fileDetails}`;
      if (additionalityResults.length > 0) {
        const addDetails = additionalityResults
          .map((a) =>
            a.result.redundancyPct < 0
              ? `${a.path}: no comparable segments`
              : `${a.path}: ${a.result.additionalityPct.toFixed(1)}% additionality, ${a.result.redundancyPct.toFixed(1)}% redundancy`,
          )
          .join("; ");
        summary += `. Additionality: ${addDetails}`;
      }
    } else {
      summary = "No agent context files found";
    }

    return buildPillarResult(PILLAR, score, "medium", findings, summary, [
      "Lulla et al., 2026 — Quality AGENTS.md reduces agent time 28.6%, tokens 16.6%",
      "GitHub Next, 2024 — Contextual grounding improves Copilot accuracy 30%+",
    ]);
  },
};
