import { type PillarId, PILLAR_NAMES, PILLAR_WEIGHTS, type Finding } from "@prontiq/schema";
import type { PillarAnalyzer, RepoContext } from "./analyzer.interface.js";

const PILLAR: PillarId = "P1";

const CONTEXT_FILES = [
  "AGENTS.md",
  "CLAUDE.md",
  ".cursorrules",
  ".cursor/rules",
  ".github/copilot-instructions.md",
  ".aider.conf.yml",
  ".aiderignore",
  ".agentignore",
  ".mcp.json",
  "mcp.config.js",
  ".claude/settings.json",
] as const;

/** Directory patterns to check (any file under these dirs counts as a match) */
const CONTEXT_DIRS = [
  ".claude/commands",
] as const;

/** Keywords that indicate critical build/test/architecture info */
const CRITICAL_INFO_PATTERNS = [
  /\b(pnpm|npm|yarn|make|cargo|go)\s+(install|build|test|run)/i,
  /\b(build|test|lint|format|typecheck)\s*(command|script|step)/i,
  /```\s*(bash|sh|shell|zsh)/i,
  /##\s*(architecture|overview|structure|getting started|setup|build|test)/i,
];

/** Patterns that suggest auto-generated/boilerplate content */
const BOILERPLATE_PATTERNS = [
  /^this project is a\b/im,
  /^this is a\b/im,
  /^welcome to\b/im,
  /^## getting started\s*\n\s*\n\s*## /im,
  /^## table of contents/im,
  /generated by /i,
  /auto-generated/i,
  /do not edit/i,
];

interface DiscoveredFile {
  path: string;
  size: number;
  lineCount: number;
}

/**
 * Check if critical information is front-loaded in the first 20% of a file.
 * Returns true if critical info is found only in the bottom 80%.
 */
function hasBuriedCriticalInfo(content: string): boolean {
  const lines = content.split("\n");
  const cutoff = Math.max(1, Math.ceil(lines.length * 0.2));
  const topSection = lines.slice(0, cutoff).join("\n");
  const bottomSection = lines.slice(cutoff).join("\n");

  // Check if critical info exists in bottom but NOT in top
  const topHasCritical = CRITICAL_INFO_PATTERNS.some((p) => p.test(topSection));
  const bottomHasCritical = CRITICAL_INFO_PATTERNS.some((p) => p.test(bottomSection));

  return !topHasCritical && bottomHasCritical;
}

/**
 * Extract file/directory path references from content.
 * Looks for patterns like `path/to/file.ts`, `./src/`, `packages/foo/`, etc.
 */
function extractReferencedPaths(content: string): string[] {
  const pathPattern = /(?:^|\s|`|")((?:\.\/|\.\.\/)?(?:[a-zA-Z0-9_-]+\/)+[a-zA-Z0-9_.-]*)/gm;
  const paths: string[] = [];
  let match: RegExpExecArray | null;
  while ((match = pathPattern.exec(content)) !== null) {
    const p = match[1]?.replace(/^\.\//, "");
    // Filter out common non-path matches
    if (p && !p.startsWith("http") && !p.startsWith("//")) {
      paths.push(p);
    }
  }
  return paths;
}

/**
 * Check if content appears to be auto-generated boilerplate without project specifics.
 */
function isLikelyBoilerplate(content: string, repoFiles: readonly string[]): boolean {
  // Check for boilerplate patterns
  const hasBoilerplateMarkers = BOILERPLATE_PATTERNS.some((p) => p.test(content));

  // Check if content references any actual repo files/directories
  const repoFilenames = new Set<string>();
  for (const f of repoFiles) {
    // Add both full path and filename parts
    const parts = f.split("/");
    for (const part of parts) {
      if (part && part.length > 2 && !part.startsWith(".")) {
        repoFilenames.add(part);
      }
    }
  }

  // Count project-specific references
  let specificRefs = 0;
  for (const name of repoFilenames) {
    if (content.includes(name)) {
      specificRefs++;
    }
  }

  // Consider it boilerplate if it has boilerplate markers AND few project-specific references
  return hasBoilerplateMarkers && specificRefs < 2;
}

export const contextQualityAnalyzer: PillarAnalyzer = {
  pillar: PILLAR,
  name: PILLAR_NAMES[PILLAR],
  version: "0.2.0",

  async supports(): Promise<boolean> {
    return true;
  },

  async analyze(context: RepoContext) {
    const findings: Finding[] = [];
    let score = 20; // Baseline: no context files = 20%

    const discoveredFiles: DiscoveredFile[] = [];
    const foundContextFiles: string[] = [];

    // Check standard context files
    for (const cf of CONTEXT_FILES) {
      const exists = await context.fileExists(cf);
      if (exists) {
        foundContextFiles.push(cf);
        const content = await context.readFile(cf);
        if (content !== null) {
          discoveredFiles.push({
            path: cf,
            size: content.length,
            lineCount: content.split("\n").length,
          });
        }
      }
    }

    // Check directory patterns
    for (const dir of CONTEXT_DIRS) {
      const hasFiles = context.files.some((f) => f.startsWith(dir + "/"));
      if (hasFiles) {
        const dirLabel = dir + "/";
        foundContextFiles.push(dirLabel);
        discoveredFiles.push({ path: dirLabel, size: 0, lineCount: 0 });
      }
    }

    // Discover nested AGENTS.md files for monorepos
    const nestedAgentsFiles = context.files.filter(
      (f) => f !== "AGENTS.md" && f.endsWith("/AGENTS.md"),
    );
    for (const nestedFile of nestedAgentsFiles) {
      if (!foundContextFiles.includes(nestedFile)) {
        foundContextFiles.push(nestedFile);
        const content = await context.readFile(nestedFile);
        if (content !== null) {
          discoveredFiles.push({
            path: nestedFile,
            size: content.length,
            lineCount: content.split("\n").length,
          });
        }
      }
    }

    if (foundContextFiles.length === 0) {
      findings.push({
        code: "ARI-CTX-001",
        severity: "high",
        pillar: PILLAR,
        message: "No agent context files found (AGENTS.md, CLAUDE.md, .cursorrules, etc.)",
        remediation: {
          action: "create-file",
          path: "AGENTS.md",
          description: "Create an AGENTS.md file with project-specific context for AI coding agents",
          estimatedImpact: "+12 points composite",
          confidence: "high",
        },
        evidence: {
          paper: "Lulla et al., 2026",
          finding: "Quality AGENTS.md reduces agent time 28.6%, tokens 16.6%",
          confidence: "high",
        },
      });
    } else {
      // Base score boost for having context files
      score += 15 * Math.min(foundContextFiles.length, 3);

      // Check AGENTS.md quality if it exists
      if (foundContextFiles.includes("AGENTS.md")) {
        const content = await context.readFile("AGENTS.md");
        if (content) {
          const lines = content.split("\n").length;
          const hasHeadings = /^#+\s/m.test(content);
          const hasCodeBlocks = /```/.test(content);
          const hasDontStatements = /\b(don't|do not|never|avoid)\b/i.test(content);

          if (lines < 10) {
            findings.push({
              code: "ARI-CTX-002",
              severity: "medium",
              pillar: PILLAR,
              message: "AGENTS.md is too short (< 10 lines). Effective context files provide detailed project-specific guidance.",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description: "Expand AGENTS.md with architecture overview, conventions, and common pitfalls",
                confidence: "high",
              },
            });
          } else {
            score += 10;
          }

          if (hasHeadings) score += 5;
          if (hasCodeBlocks) score += 5;
          if (hasDontStatements) score += 5; // Negative instructions are valuable

          // Front-loading check (ARI-CTX-005) for AGENTS.md
          if (lines >= 10 && hasBuriedCriticalInfo(content)) {
            findings.push({
              code: "ARI-CTX-005",
              severity: "medium",
              pillar: PILLAR,
              message: "AGENTS.md has critical info (build commands, architecture) buried below the first 20% of the file. Front-load important context for better agent performance.",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description: "Move build commands, test commands, and architecture overview to the top of AGENTS.md",
                confidence: "medium",
              },
            });
            score -= 5;
          }

          // Staleness detection (ARI-CTX-006)
          const referencedPaths = extractReferencedPaths(content);
          const fileSet = new Set(context.files);
          const stalePaths: string[] = [];
          for (const rp of referencedPaths) {
            // Check if the referenced path exists as a file or as a directory prefix
            const rpClean = rp.replace(/\/$/, "");
            const existsAsFile = fileSet.has(rpClean);
            const existsAsDir = context.files.some(
              (f) => f.startsWith(rpClean + "/"),
            );
            if (!existsAsFile && !existsAsDir) {
              stalePaths.push(rp);
            }
          }
          if (stalePaths.length > 0) {
            findings.push({
              code: "ARI-CTX-006",
              severity: "low",
              pillar: PILLAR,
              message: `AGENTS.md references ${stalePaths.length} path(s) not found in the repo: ${stalePaths.slice(0, 3).join(", ")}${stalePaths.length > 3 ? "..." : ""}. Content may be stale.`,
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description: "Review and update AGENTS.md to remove or fix references to non-existent paths",
                confidence: "low",
              },
            });
            score -= 3;
          }

          // Boilerplate detection (ARI-CTX-007)
          if (isLikelyBoilerplate(content, context.files)) {
            findings.push({
              code: "ARI-CTX-007",
              severity: "medium",
              pillar: PILLAR,
              message: "AGENTS.md appears to contain auto-generated or boilerplate content without project-specific details.",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description: "Replace boilerplate content with project-specific architecture, conventions, and build instructions",
                confidence: "medium",
              },
            });
            score -= 10;
          }

          // Conciseness check (ARI-CTX-008)
          if (lines > 500) {
            const codeBlockMatches = content.match(/```/g);
            const codeBlockCount = codeBlockMatches ? Math.floor(codeBlockMatches.length / 2) : 0;
            // Expect roughly 1 code block per 50 lines for well-structured docs
            const expectedBlocks = Math.floor(lines / 50);
            if (codeBlockCount < expectedBlocks / 2) {
              findings.push({
                code: "ARI-CTX-008",
                severity: "low",
                pillar: PILLAR,
                message: `AGENTS.md is very long (${lines} lines) without proportional code examples. Verbose context files can reduce agent efficiency.`,
                remediation: {
                  action: "modify-config",
                  path: "AGENTS.md",
                  description: "Condense AGENTS.md or add more code examples to justify the length",
                  confidence: "medium",
                },
              });
              score -= 5;
            }
          }
        }
      }

      // Front-loading check for CLAUDE.md
      if (foundContextFiles.includes("CLAUDE.md")) {
        const claudeContent = await context.readFile("CLAUDE.md");
        if (claudeContent) {
          const claudeLines = claudeContent.split("\n").length;
          if (claudeLines >= 10 && hasBuriedCriticalInfo(claudeContent)) {
            findings.push({
              code: "ARI-CTX-005",
              severity: "medium",
              pillar: PILLAR,
              message: "CLAUDE.md has critical info (build commands, architecture) buried below the first 20% of the file. Front-load important context for better agent performance.",
              remediation: {
                action: "modify-config",
                path: "CLAUDE.md",
                description: "Move build commands, test commands, and architecture overview to the top of CLAUDE.md",
                confidence: "medium",
              },
            });
            score -= 5;
          }
        }
      }

      // Check for .agentignore
      if (foundContextFiles.includes(".agentignore")) {
        score += 10;
      } else {
        findings.push({
          code: "ARI-CTX-003",
          severity: "low",
          pillar: PILLAR,
          message: "No .agentignore file found. This file helps agents exclude irrelevant files from context.",
          remediation: {
            action: "create-file",
            path: ".agentignore",
            description: "Create .agentignore to exclude generated files, vendor code, and binaries from agent context",
            confidence: "medium",
          },
        });
      }
    }

    // Check README quality as context baseline
    const readme = await context.readFile("README.md");
    if (readme) {
      const readmeLines = readme.split("\n").length;
      if (readmeLines > 20) score += 5;
    } else {
      findings.push({
        code: "ARI-CTX-004",
        severity: "medium",
        pillar: PILLAR,
        message: "No README.md found. README serves as baseline context for all agents.",
        remediation: {
          action: "create-file",
          path: "README.md",
          description: "Create a README.md with project overview, setup instructions, and architecture summary",
          confidence: "high",
        },
      });
    }

    score = Math.min(100, Math.max(0, score));

    // Build summary with file metadata
    let summary: string;
    if (discoveredFiles.length > 0) {
      const fileDetails = discoveredFiles
        .map((f) =>
          f.size > 0
            ? `${f.path} (${f.lineCount} lines, ${f.size} bytes)`
            : `${f.path} (directory)`,
        )
        .join(", ");
      summary = `Found ${foundContextFiles.length} context file(s): ${fileDetails}`;
    } else {
      summary = "No agent context files found";
    }

    return {
      pillar: PILLAR,
      name: PILLAR_NAMES[PILLAR],
      score,
      weight: PILLAR_WEIGHTS[PILLAR],
      confidence: "medium",
      findings,
      summary,
    };
  },
};
