import { type PillarId, PILLAR_NAMES, type Finding } from "@prontiq/ariscan-schema";
import type { PillarAnalyzer, RepoContext } from "./analyzer.interface.js";
import { buildPillarResult } from "./shared.js";
import {
  computeAdditionality,
  hasBuriedCriticalInfo,
  normalizeConfigContent,
  extractLeadingDocstring,
  REFERENCE_DOC_PATHS,
  REFERENCE_CONFIG_PATHS,
  DYNAMIC_CONFIG_PATTERNS,
  SOURCE_EXTENSIONS,
  MAX_SOURCE_FILES_FOR_DOCSTRINGS,
  CI_WORKFLOW_PREFIXES,
  type AdditionalityResult,
} from "../context/additionality.js";

const PILLAR: PillarId = "P1";

const CONTEXT_FILES = [
  "AGENTS.md",
  "CLAUDE.md",
  ".cursorrules",
  ".cursor/rules",
  ".github/copilot-instructions.md",
  ".aider.conf.yml",
  ".aiderignore",
  ".agentignore",
  ".mcp.json",
  "mcp.config.js",
  ".claude/settings.json",
] as const;

/** Directory patterns to check (any file under these dirs counts as a match) */
const CONTEXT_DIRS = [".claude/commands"] as const;

/** Agent-to-context-file mapping for cross-agent compatibility report */
interface AgentMapping {
  agent: string;
  files: readonly string[];
  dirs?: readonly string[];
}

const AGENT_MAPPINGS: readonly AgentMapping[] = [
  {
    agent: "Claude Code",
    files: ["CLAUDE.md", ".claude/settings.json"],
    dirs: [".claude/commands"],
  },
  {
    agent: "Cursor",
    files: [".cursorrules", ".cursor/rules"],
  },
  {
    agent: "GitHub Copilot",
    files: [".github/copilot-instructions.md"],
  },
  {
    agent: "Aider",
    files: [".aider.conf.yml", ".aiderignore"],
  },
  {
    agent: "Generic (all agents)",
    files: ["AGENTS.md", ".agentignore"],
  },
] as const;

/** Patterns that suggest auto-generated/boilerplate content */
const BOILERPLATE_PATTERNS = [
  /^this project is a\b/im,
  /^this is a\b/im,
  /^welcome to\b/im,
  /^## getting started[ \t]*\n[ \t]*\n[ \t]*## /im,
  /^## table of contents/im,
  /generated by /i,
  /auto-generated/i,
  /do not edit/i,
];

interface DiscoveredFile {
  path: string;
  size: number;
  lineCount: number;
}

/**
 * Extract file/directory path references from content.
 * Looks for patterns like `path/to/file.ts`, `./src/`, `packages/foo/`, etc.
 */
function extractReferencedPaths(content: string): string[] {
  const pathPattern = /(?:^|[\s`"])((?:\.\.?\/)?[a-zA-Z0-9_-]+\/[a-zA-Z0-9_./-]*)/gm;
  const paths: string[] = [];
  let match: RegExpExecArray | null;
  while ((match = pathPattern.exec(content)) !== null) {
    const p = match[1]?.replace(/^\.\//, "");
    // Filter out common non-path matches
    if (p && !p.startsWith("http") && !p.startsWith("//")) {
      paths.push(p);
    }
  }
  return paths;
}

/**
 * Check if content appears to be auto-generated boilerplate without project specifics.
 */
function isLikelyBoilerplate(content: string, repoFiles: readonly string[]): boolean {
  // Check for boilerplate patterns
  const hasBoilerplateMarkers = BOILERPLATE_PATTERNS.some((p) => p.test(content));

  // Check if content references any actual repo files/directories
  const repoFilenames = new Set<string>();
  for (const f of repoFiles) {
    // Add both full path and filename parts
    const parts = f.split("/");
    for (const part of parts) {
      if (part && part.length > 2 && !part.startsWith(".")) {
        repoFilenames.add(part);
      }
    }
  }

  // Count project-specific references
  let specificRefs = 0;
  for (const name of repoFilenames) {
    if (content.includes(name)) {
      specificRefs++;
    }
  }

  // Consider it boilerplate if it has boilerplate markers AND few project-specific references
  return hasBoilerplateMarkers && specificRefs < 2;
}

export const contextQualityAnalyzer: PillarAnalyzer = {
  pillar: PILLAR,
  name: PILLAR_NAMES[PILLAR],
  version: "0.2.0",

  async supports(): Promise<boolean> {
    return true;
  },

  async analyze(context: RepoContext) {
    const findings: Finding[] = [];
    let score = 20; // Baseline: no context files = 20%

    const discoveredFiles: DiscoveredFile[] = [];
    const foundContextFiles: string[] = [];

    // Check standard context files
    for (const cf of CONTEXT_FILES) {
      const exists = await context.fileExists(cf);
      if (exists) {
        foundContextFiles.push(cf);
        const content = await context.readFile(cf);
        if (content !== null) {
          discoveredFiles.push({
            path: cf,
            size: content.length,
            lineCount: content.split("\n").length,
          });
        }
      }
    }

    // Check directory patterns
    for (const dir of CONTEXT_DIRS) {
      const hasFiles = context.files.some((f) => f.startsWith(dir + "/"));
      if (hasFiles) {
        const dirLabel = dir + "/";
        foundContextFiles.push(dirLabel);
        discoveredFiles.push({ path: dirLabel, size: 0, lineCount: 0 });
      }
    }

    // Discover nested AGENTS.md files for monorepos
    const nestedAgentsFiles = context.files.filter(
      (f) => f !== "AGENTS.md" && f.endsWith("/AGENTS.md"),
    );
    for (const nestedFile of nestedAgentsFiles) {
      if (!foundContextFiles.includes(nestedFile)) {
        foundContextFiles.push(nestedFile);
        const content = await context.readFile(nestedFile);
        if (content !== null) {
          discoveredFiles.push({
            path: nestedFile,
            size: content.length,
            lineCount: content.split("\n").length,
          });
        }
      }
    }

    if (foundContextFiles.length === 0) {
      findings.push({
        code: "ARI-CTX-001",
        severity: "high",
        pillar: PILLAR,
        message: "No agent context files found (AGENTS.md, CLAUDE.md, .cursorrules, etc.)",
        confidence: "high",
        remediation: {
          action: "create-file",
          path: "AGENTS.md",
          description:
            "Create an AGENTS.md file with project-specific context for AI coding agents",
          estimatedImpact: "+12 points composite",
          confidence: "high",
        },
        evidence: {
          paper: "Lulla et al., 2026",
          finding: "Quality AGENTS.md reduces agent time 28.6%, tokens 16.6%",
          confidence: "high",
        },
      });
    } else {
      // Base score boost for having context files
      score += 15 * Math.min(foundContextFiles.length, 3);

      // Check AGENTS.md quality if it exists
      if (foundContextFiles.includes("AGENTS.md")) {
        const content = await context.readFile("AGENTS.md");
        if (content) {
          const lines = content.split("\n").length;
          const hasHeadings = /^#+\s/m.test(content);
          const hasCodeBlocks = /```/.test(content);
          const hasDontStatements = /\b(don't|do not|never|avoid)\b/i.test(content);

          if (lines < 10) {
            findings.push({
              code: "ARI-CTX-002",
              severity: "medium",
              pillar: PILLAR,
              message:
                "AGENTS.md is too short (< 10 lines). Effective context files provide detailed project-specific guidance.",
              confidence: "medium",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description:
                  "Expand AGENTS.md with architecture overview, conventions, and common pitfalls",
                confidence: "high",
              },
            });
          } else {
            score += 10;
          }

          if (hasHeadings) score += 5;
          if (hasCodeBlocks) score += 5;
          if (hasDontStatements) score += 5; // Negative instructions are valuable

          // Front-loading check (ARI-CTX-005) for AGENTS.md
          if (lines >= 10 && hasBuriedCriticalInfo(content)) {
            findings.push({
              code: "ARI-CTX-005",
              severity: "medium",
              pillar: PILLAR,
              message:
                "AGENTS.md has critical info (build commands, architecture) buried below the first 20% of the file. Front-load important context for better agent performance.",
              confidence: "medium",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description:
                  "Move build commands, test commands, and architecture overview to the top of AGENTS.md",
                confidence: "medium",
              },
            });
            score -= 5;
          }

          // Staleness detection (ARI-CTX-006)
          const referencedPaths = extractReferencedPaths(content);
          const fileSet = new Set(context.files);
          const stalePaths: string[] = [];
          for (const rp of referencedPaths) {
            // Check if the referenced path exists as a file or as a directory prefix
            const rpClean = rp.replace(/\/$/, "");
            const existsAsFile = fileSet.has(rpClean);
            const existsAsDir = context.files.some((f) => f.startsWith(rpClean + "/"));
            if (!existsAsFile && !existsAsDir) {
              stalePaths.push(rp);
            }
          }
          if (stalePaths.length > 0) {
            findings.push({
              code: "ARI-CTX-006",
              severity: "low",
              pillar: PILLAR,
              message: `AGENTS.md references ${stalePaths.length} path(s) not found in the repo: ${stalePaths.slice(0, 3).join(", ")}${stalePaths.length > 3 ? "..." : ""}. Content may be stale.`,
              confidence: "medium",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description:
                  "Review and update AGENTS.md to remove or fix references to non-existent paths",
                confidence: "low",
              },
            });
            score -= 3;
          }

          // Boilerplate detection (ARI-CTX-007)
          if (isLikelyBoilerplate(content, context.files)) {
            findings.push({
              code: "ARI-CTX-007",
              severity: "medium",
              pillar: PILLAR,
              message:
                "AGENTS.md appears to contain auto-generated or boilerplate content without project-specific details.",
              confidence: "low",
              remediation: {
                action: "modify-config",
                path: "AGENTS.md",
                description:
                  "Replace boilerplate content with project-specific architecture, conventions, and build instructions",
                confidence: "medium",
              },
            });
            score -= 10;
          }

          // Conciseness check (ARI-CTX-008)
          if (lines > 500) {
            const codeBlockMatches = content.match(/```/g);
            const codeBlockCount = codeBlockMatches ? Math.floor(codeBlockMatches.length / 2) : 0;
            // Expect roughly 1 code block per 50 lines for well-structured docs
            const expectedBlocks = Math.floor(lines / 50);
            if (codeBlockCount < expectedBlocks / 2) {
              findings.push({
                code: "ARI-CTX-008",
                severity: "low",
                pillar: PILLAR,
                message: `AGENTS.md is very long (${lines} lines) without proportional code examples. Verbose context files can reduce agent efficiency.`,
                confidence: "low",
                remediation: {
                  action: "modify-config",
                  path: "AGENTS.md",
                  description: "Condense AGENTS.md or add more code examples to justify the length",
                  confidence: "medium",
                },
              });
              score -= 5;
            }
          }
        }
      }

      // Front-loading check for CLAUDE.md
      if (foundContextFiles.includes("CLAUDE.md")) {
        const claudeContent = await context.readFile("CLAUDE.md");
        if (claudeContent) {
          const claudeLines = claudeContent.split("\n").length;
          if (claudeLines >= 10 && hasBuriedCriticalInfo(claudeContent)) {
            findings.push({
              code: "ARI-CTX-005",
              severity: "medium",
              pillar: PILLAR,
              message:
                "CLAUDE.md has critical info (build commands, architecture) buried below the first 20% of the file. Front-load important context for better agent performance.",
              confidence: "medium",
              remediation: {
                action: "modify-config",
                path: "CLAUDE.md",
                description:
                  "Move build commands, test commands, and architecture overview to the top of CLAUDE.md",
                confidence: "medium",
              },
            });
            score -= 5;
          }
        }
      }

      // Check for .agentignore
      if (foundContextFiles.includes(".agentignore")) {
        score += 10;
      } else {
        findings.push({
          code: "ARI-CTX-003",
          severity: "low",
          pillar: PILLAR,
          message:
            "No .agentignore file found. This file helps agents exclude irrelevant files from context.",
          confidence: "high",
          remediation: {
            action: "create-file",
            path: ".agentignore",
            description:
              "Create .agentignore to exclude generated files, vendor code, and binaries from agent context",
            confidence: "medium",
          },
        });
      }
    }

    // --- ARI-CTX-009: Non-parsable context file warnings ---
    // Validate parse status for structured context files (JSON, YAML)
    const nonParsableFiles: Array<{ path: string; reason: string }> = [];
    for (const cf of foundContextFiles) {
      const content = await context.readFile(cf);
      if (content === null) continue;

      if (cf.endsWith(".json")) {
        try {
          JSON.parse(content);
        } catch {
          nonParsableFiles.push({ path: cf, reason: "invalid JSON" });
        }
      } else if (cf.endsWith(".yml") || cf.endsWith(".yaml")) {
        const trimmed = content.trim();
        if (trimmed.length === 0) {
          nonParsableFiles.push({ path: cf, reason: "empty YAML file" });
        } else if (/^\t+ /m.test(trimmed) || /^ +\t/m.test(trimmed)) {
          nonParsableFiles.push({ path: cf, reason: "mixed tabs and spaces in YAML" });
        }
      }

      // Check for completely empty files (any type)
      if (content.trim().length === 0 && !cf.endsWith(".yml") && !cf.endsWith(".yaml")) {
        nonParsableFiles.push({ path: cf, reason: "empty file" });
      }
    }

    if (nonParsableFiles.length > 0) {
      score -= 5 * nonParsableFiles.length;
      const details = nonParsableFiles
        .slice(0, 3)
        .map((f) => `${f.path} (${f.reason})`)
        .join(", ");
      findings.push({
        code: "ARI-CTX-009",
        severity: "high",
        pillar: PILLAR,
        message: `${nonParsableFiles.length} context file(s) failed parse validation: ${details}${nonParsableFiles.length > 3 ? ` and ${nonParsableFiles.length - 3} more` : ""}`,
        confidence: "high",
        remediation: {
          action: "modify-config",
          description:
            "Fix parse errors in context files. Invalid JSON or malformed YAML will prevent agents from reading configuration correctly.",
          confidence: "high",
        },
      });
    }

    // --- ARI-CTX-010: Cross-agent compatibility report ---
    const coveredAgents: string[] = [];
    const uncoveredAgents: string[] = [];

    for (const mapping of AGENT_MAPPINGS) {
      const hasFile = mapping.files.some((f) => foundContextFiles.includes(f));
      const hasDir = mapping.dirs?.some((d) => foundContextFiles.includes(d + "/")) ?? false;

      if (hasFile || hasDir) {
        coveredAgents.push(mapping.agent);
      } else {
        uncoveredAgents.push(mapping.agent);
      }
    }

    if (uncoveredAgents.length > 0 && foundContextFiles.length > 0) {
      findings.push({
        code: "ARI-CTX-010",
        severity: "info",
        pillar: PILLAR,
        message: `Agent context coverage: ${coveredAgents.length}/${AGENT_MAPPINGS.length} agents covered. Missing: ${uncoveredAgents.join(", ")}.`,
        confidence: "high",
        remediation: {
          action: "create-file",
          description: `Add context files for uncovered agents: ${uncoveredAgents.join(", ")}. Use AGENTS.md for vendor-neutral context that all agents can read.`,
          confidence: "medium",
        },
      });
    } else if (foundContextFiles.length === 0) {
      findings.push({
        code: "ARI-CTX-010",
        severity: "medium",
        pillar: PILLAR,
        message: `Agent context coverage: 0/${AGENT_MAPPINGS.length} agents covered. No agent has dedicated context files.`,
        confidence: "high",
        remediation: {
          action: "create-file",
          path: "AGENTS.md",
          description:
            "Start with AGENTS.md for vendor-neutral context, then add agent-specific files (CLAUDE.md, .cursorrules, etc.) as needed.",
          confidence: "high",
        },
      });
    }

    // Check README quality as context baseline
    const readme = await context.readFile("README.md");
    if (readme) {
      const readmeLines = readme.split("\n").length;
      if (readmeLines > 20) score += 5;
    } else {
      findings.push({
        code: "ARI-CTX-004",
        severity: "medium",
        pillar: PILLAR,
        message: "No README.md found. README serves as baseline context for all agents.",
        confidence: "high",
        remediation: {
          action: "create-file",
          path: "README.md",
          description:
            "Create a README.md with project overview, setup instructions, and architecture summary",
          confidence: "high",
        },
      });
    }

    // --- Additionality analysis (P1.04) ---
    // Gather reference documents for comparison
    const referenceDocs: Array<{ path: string; content: string }> = [];
    for (const refPath of REFERENCE_DOC_PATHS) {
      const content = await context.readFile(refPath);
      if (content) {
        referenceDocs.push({ path: refPath, content });
      }
    }
    // Gather CI workflow files
    for (const prefix of CI_WORKFLOW_PREFIXES) {
      for (const f of context.files) {
        if (f.startsWith(prefix) && (f.endsWith(".yml") || f.endsWith(".yaml"))) {
          const content = await context.readFile(f);
          if (content) {
            referenceDocs.push({ path: f, content });
          }
        }
      }
    }
    // Include package.json scripts section as reference
    const pkgJson = await context.readJson<{
      description?: string;
      scripts?: Record<string, string>;
    }>("package.json");
    if (pkgJson) {
      const parts: string[] = [];
      if (pkgJson.description) parts.push(pkgJson.description);
      if (pkgJson.scripts) {
        for (const [key, val] of Object.entries(pkgJson.scripts)) {
          parts.push(`${key}: ${val}`);
        }
      }
      if (parts.length > 0) {
        referenceDocs.push({ path: "package.json", content: parts.join("\n") });
      }
    }
    // Include config files in reference corpus (normalized for comparison)
    for (const cfgPath of REFERENCE_CONFIG_PATHS) {
      const content = await context.readFile(cfgPath);
      if (content) {
        referenceDocs.push({ path: cfgPath, content: normalizeConfigContent(content, cfgPath) });
      }
    }
    // Also include eslint/prettier config files found by pattern (including nested paths)
    for (const f of context.files) {
      const bn = f.includes("/") ? f.slice(f.lastIndexOf("/") + 1) : f;
      if (
        (bn.match(/^\.eslintrc(\.[a-z]+)?$/) ||
          bn.match(/^\.prettierrc(\.[a-z]+)?$/) ||
          bn === "eslint.config.js" ||
          bn === "eslint.config.mjs" ||
          bn === "prettier.config.js" ||
          bn === "prettier.config.mjs") &&
        !referenceDocs.some((d) => d.path === f) &&
        !/(?:^|\/)(node_modules|dist|build)\//.test(f)
      ) {
        const content = await context.readFile(f);
        if (content) {
          referenceDocs.push({ path: f, content: normalizeConfigContent(content, f) });
        }
      }
    }
    // Include dynamically-discovered config files matching common patterns
    // Match on basename so monorepo nested configs (e.g. packages/foo/vitest.config.ts) are included
    for (const f of context.files) {
      if (referenceDocs.some((d) => d.path === f)) continue;
      // Skip files inside node_modules, dist, or build directories
      if (/(?:^|\/)(node_modules|dist|build|\.next|\.nuxt)\//.test(f)) continue;
      const basename = f.includes("/") ? f.slice(f.lastIndexOf("/") + 1) : f;
      if (DYNAMIC_CONFIG_PATTERNS.some((p) => p.test(basename))) {
        const content = await context.readFile(f);
        if (content) {
          referenceDocs.push({ path: f, content: normalizeConfigContent(content, f) });
        }
      }
    }

    // Extract leading docstrings/comments from source files
    let docstringCount = 0;
    for (const f of context.files) {
      if (docstringCount >= MAX_SOURCE_FILES_FOR_DOCSTRINGS) break;
      if (!SOURCE_EXTENSIONS.some((ext) => f.endsWith(ext))) continue;
      // Skip test files and generated files
      if (f.includes("__tests__") || f.includes(".test.") || f.includes(".spec.")) continue;
      if (f.includes("node_modules/") || f.includes("dist/") || f.includes("build/")) continue;
      const content = await context.readFile(f);
      if (!content) continue;
      const docstring = extractLeadingDocstring(content);
      if (docstring && docstring.length > 50) {
        referenceDocs.push({ path: f, content: docstring });
        docstringCount++;
      }
    }

    // Run additionality analysis on text-based context files
    const TEXT_CONTEXT_FILES = [
      "AGENTS.md",
      "CLAUDE.md",
      ".cursorrules",
      ".cursor/rules",
      ".github/copilot-instructions.md",
    ];
    const additionalityResults: Array<{
      path: string;
      result: AdditionalityResult;
    }> = [];

    if (referenceDocs.length > 0) {
      for (const cf of foundContextFiles) {
        if (!TEXT_CONTEXT_FILES.includes(cf) && !cf.endsWith("/AGENTS.md")) continue;
        const content = await context.readFile(cf);
        if (!content || content.trim().length === 0) continue;

        // For nested AGENTS.md files, augment the corpus with package-local docs
        let effectiveRefDocs = referenceDocs;
        if (cf.endsWith("/AGENTS.md") && cf !== "AGENTS.md") {
          // Walk upward from the AGENTS.md path to find the nearest package root.
          // Prefer package.json (strongest signal) over README-bearing directories,
          // so that layouts like packages/foo/docs/AGENTS.md resolve to packages/foo/
          // even when packages/foo/docs/README.md exists.
          const parts = cf.split("/");
          parts.pop(); // remove "AGENTS.md"
          let pkgDir = parts.join("/") + "/"; // start from immediate parent

          // Pass 1: walk upward looking for a directory with package.json
          const partsForPkg = [...parts];
          let foundPkgJson = false;
          while (partsForPkg.length > 0) {
            const candidate = partsForPkg.join("/") + "/";
            const hasPkgJson = context.files.some((f) => {
              if (!f.startsWith(candidate)) return false;
              const rest = f.slice(candidate.length);
              return rest === "package.json";
            });
            if (hasPkgJson) {
              pkgDir = candidate;
              foundPkgJson = true;
              break;
            }
            partsForPkg.pop();
          }

          // Pass 2 (fallback): if no package.json found, look for README/CONTRIBUTING
          if (!foundPkgJson) {
            const partsForReadme = [...parts];
            while (partsForReadme.length > 0) {
              const candidate = partsForReadme.join("/") + "/";
              const hasBoundary = context.files.some((f) => {
                if (!f.startsWith(candidate)) return false;
                const rest = f.slice(candidate.length);
                if (rest.includes("/")) return false;
                const upper = rest.toUpperCase();
                return upper.startsWith("README") || upper.startsWith("CONTRIBUTING");
              });
              if (hasBoundary) {
                pkgDir = candidate;
                break;
              }
              partsForReadme.pop();
            }
          }
          const localDocs: Array<{ path: string; content: string }> = [];
          // Gather README* and CONTRIBUTING* files from the package root
          for (const f of context.files) {
            if (!f.startsWith(pkgDir)) continue;
            // Only direct children (no further nesting)
            const rest = f.slice(pkgDir.length);
            if (rest.includes("/")) continue;
            const upper = rest.toUpperCase();
            if (
              (upper.startsWith("README") || upper.startsWith("CONTRIBUTING")) &&
              !referenceDocs.some((d) => d.path === f)
            ) {
              const localContent = await context.readFile(f);
              if (localContent) {
                localDocs.push({ path: f, content: localContent });
              }
            }
          }
          // Gather package.json description/scripts from the package root
          const localPkgPath = `${pkgDir}package.json`;
          if (!referenceDocs.some((d) => d.path === localPkgPath)) {
            const localPkg = await context.readJson<{
              description?: string;
              scripts?: Record<string, string>;
            }>(localPkgPath);
            if (localPkg) {
              const parts: string[] = [];
              if (localPkg.description) parts.push(localPkg.description);
              if (localPkg.scripts) {
                for (const [key, val] of Object.entries(localPkg.scripts)) {
                  parts.push(`${key}: ${val}`);
                }
              }
              if (parts.length > 0) {
                localDocs.push({ path: localPkgPath, content: parts.join("\n") });
              }
            }
          }
          if (localDocs.length > 0) {
            effectiveRefDocs = [...referenceDocs, ...localDocs];
          }
        }

        const result = computeAdditionality(content, cf, effectiveRefDocs);
        additionalityResults.push({ path: cf, result });

        // Skip scoring when no comparable segments were analyzed (indeterminate)
        if (result.redundancyPct < 0) {
          // No segments to compare — do not award bonus or apply penalty
        } else if (result.redundancyPct > 50) {
          // ARI-CTX-011: High redundancy
          const topDuplicates = result.duplicateLines
            .slice(0, 3)
            .map((d) => `L${d.line}: "${d.text}" (similar to ${d.matchedIn})`)
            .join("; ");
          const topAdditive = result.additiveLines
            .slice(0, 3)
            .map((a) => `L${a.line}: "${a.text}"`)
            .join("; ");

          findings.push({
            code: "ARI-CTX-011",
            severity: result.redundancyPct > 70 ? "medium" : "low",
            pillar: PILLAR,
            file: cf,
            message: [
              `${cf} has ${result.redundancyPct.toFixed(1)}% content redundancy with existing repo documentation.`,
              result.methodology,
              topDuplicates ? `Duplicative: ${topDuplicates}.` : "",
              topAdditive ? `Additive: ${topAdditive}.` : "",
            ]
              .filter(Boolean)
              .join(" "),
            confidence: "medium",
            remediation: {
              action: "modify-config",
              path: cf,
              description:
                "Remove content that duplicates README, CONTRIBUTING, or CI config. Focus on project-specific guidance that agents cannot discover through file traversal.",
              estimatedImpact: "+5-10 points composite",
              confidence: "medium",
            },
            evidence: {
              paper: "Gloaguen et al., 2026",
              finding:
                "LLM-generated context files that duplicate README decrease agent success by 2-3% while increasing inference cost by 20%+",
              confidence: "high",
            },
          });

          // Score deduction based on redundancy level
          if (result.redundancyPct > 70) {
            score -= 10;
          } else {
            score -= 5;
          }
        } else if (result.redundancyPct > 30) {
          // ARI-CTX-011: Moderate redundancy — emit info-level finding with deduction
          findings.push({
            code: "ARI-CTX-011",
            severity: "info",
            pillar: PILLAR,
            file: cf,
            message: [
              `${cf} has ${result.redundancyPct.toFixed(1)}% content redundancy with existing repo documentation.`,
              result.methodology,
              "Consider reducing overlap with README or CONTRIBUTING to improve additionality.",
            ].join(" "),
            confidence: "low",
            remediation: {
              action: "modify-config",
              path: cf,
              description:
                "Review content that overlaps with README, CONTRIBUTING, or CI config. Remove duplicated sections and focus on project-specific guidance.",
              confidence: "low",
            },
          });
          score -= 3;
        }

        // Additionality bonus for high-quality context (only when measurable)
        if (result.additionalityPct > 80) {
          score += 5;
        }

        // ARI-CTX-012: LLM-generated file duplicating README
        if (result.redundancyPct > 70 && content && isLikelyBoilerplate(content, context.files)) {
          findings.push({
            code: "ARI-CTX-012",
            severity: "high",
            pillar: PILLAR,
            file: cf,
            message: `${cf} appears to be LLM-generated content that duplicates existing documentation (${result.redundancyPct.toFixed(1)}% redundancy). Auto-generated context files hurt agent performance.`,
            confidence: "medium",
            remediation: {
              action: "modify-config",
              path: cf,
              description:
                "Replace auto-generated content with hand-written, project-specific context. Focus on architecture decisions, conventions, and pitfalls that are not documented elsewhere.",
              estimatedImpact: "+10-15 points composite",
              confidence: "high",
            },
            evidence: {
              paper: "Gloaguen et al., 2026",
              finding:
                "LLM-generated files decrease agent success by 2-3%, human-written files improve by ~4% on niche repos",
              confidence: "high",
            },
          });
          score -= 10; // Additional penalty for LLM-generated duplicate
        }
      }
    }

    // Build summary with file metadata and additionality
    let summary: string;
    if (discoveredFiles.length > 0) {
      const fileDetails = discoveredFiles
        .map((f) =>
          f.size > 0
            ? `${f.path} (${f.lineCount} lines, ${f.size} bytes)`
            : `${f.path} (directory)`,
        )
        .join(", ");
      summary = `Found ${foundContextFiles.length} context file(s): ${fileDetails}`;
      if (additionalityResults.length > 0) {
        const addDetails = additionalityResults
          .map((a) =>
            a.result.redundancyPct < 0
              ? `${a.path}: no comparable segments`
              : `${a.path}: ${a.result.additionalityPct.toFixed(1)}% additionality, ${a.result.redundancyPct.toFixed(1)}% redundancy`,
          )
          .join("; ");
        summary += `. Additionality: ${addDetails}`;
      }
    } else {
      summary = "No agent context files found";
    }

    return buildPillarResult(PILLAR, score, "medium", findings, summary, [
      "Lulla et al., 2026 — Quality AGENTS.md reduces agent time 28.6%, tokens 16.6%",
      "GitHub Next, 2024 — Contextual grounding improves Copilot accuracy 30%+",
    ]);
  },
};
